# Generated by Django 5.2.14 on 2026-05-12 21:53

import core.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveBigIntegerField()),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("ZOHO_CRM", "Zoho CRM"),
                            ("FLYWIRE", "Flywire"),
                            ("WORDPRESS_SITE", "WordPress site"),
                            ("LEGACY_DOTNET", "Legacy .NET"),
                        ],
                        max_length=32,
                    ),
                ),
                ("external_id", models.CharField(blank=True, db_index=True, max_length=128)),
                ("external_url", models.URLField(blank=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("PUSH", "Push"),
                            ("PULL", "Pull"),
                            ("BIDIRECTIONAL", "Bidirectional"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_SYNC", "In sync"),
                            ("DRIFT", "Drift"),
                            ("ERROR", "Error"),
                            ("DISABLED", "Disabled"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("last_pushed_at", models.DateTimeField(blank=True, null=True)),
                ("last_pulled_at", models.DateTimeField(blank=True, null=True)),
                ("last_drift_at", models.DateTimeField(blank=True, null=True)),
                ("local_fingerprint", models.CharField(blank=True, max_length=128)),
                ("remote_fingerprint", models.CharField(blank=True, max_length=128)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="contenttypes.contenttype"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("ZOHO_CRM", "Zoho CRM"),
                            ("FLYWIRE", "Flywire"),
                            ("WORDPRESS_SITE", "WordPress site"),
                            ("LEGACY_DOTNET", "Legacy .NET"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("PUSH", "Push"),
                            ("PULL", "Pull"),
                            ("BIDIRECTIONAL", "Bidirectional"),
                        ],
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("PARTIAL", "Partial"),
                        ],
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                ("records_processed", models.PositiveIntegerField(default=0)),
                ("records_succeeded", models.PositiveIntegerField(default=0)),
                ("records_failed", models.PositiveIntegerField(default=0)),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[
                            ("SCHEDULE", "Schedule"),
                            ("MANUAL", "Manual"),
                            ("SIGNAL", "Signal"),
                        ],
                        default="SCHEDULE",
                        max_length=16,
                    ),
                ),
                ("error_summary", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SyncIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("DRIFT", "Drift"),
                            ("CONFLICT", "Conflict"),
                            ("MISSING_REMOTE", "Missing remote"),
                            ("MISSING_LOCAL", "Missing local"),
                            ("VALIDATION", "Validation"),
                            ("TRANSIENT_ERROR", "Transient error"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("INFO", "Info"), ("WARNING", "Warning"), ("ERROR", "Error")],
                        default="WARNING",
                        max_length=16,
                    ),
                ),
                ("local_state", models.JSONField(blank=True, default=dict)),
                ("remote_state", models.JSONField(blank=True, default=dict)),
                ("message", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution", models.TextField(blank=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issues",
                        to="integrations.syncrecord",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="integrations.syncrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OAuthCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(choices=[("ZOHO_CRM", "Zoho CRM")], max_length=32)),
                ("account_label", models.CharField(blank=True, max_length=128)),
                ("access_token", core.fields.EncryptedTextField(blank=True, default="")),
                ("refresh_token", core.fields.EncryptedTextField(blank=True, default="")),
                ("token_type", models.CharField(default="Bearer", max_length=32)),
                ("expires_at", models.DateTimeField()),
                ("scope", models.CharField(blank=True, max_length=512)),
                ("account_id", models.CharField(blank=True, max_length=128)),
                ("connected_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("disconnected_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "connected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="oauth_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["provider", "is_active"], name="integration_provide_004d6e_idx"
                    ),
                    models.Index(fields=["expires_at"], name="integration_expires_7bb010_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("provider",),
                        name="unique_active_oauth_per_provider",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="syncrecord",
            index=models.Index(
                fields=["provider", "status"], name="integration_provide_c67755_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncrecord",
            index=models.Index(
                fields=["content_type", "object_id"], name="integration_content_619424_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncrecord",
            index=models.Index(fields=["external_id"], name="integration_externa_c98912_idx"),
        ),
        migrations.AddConstraint(
            model_name="syncrecord",
            constraint=models.UniqueConstraint(
                fields=("content_type", "object_id", "provider"),
                name="unique_sync_record_per_target_provider",
            ),
        ),
        migrations.AddConstraint(
            model_name="syncrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id__gt", "")),
                fields=("provider", "external_id"),
                name="unique_sync_record_external_id_per_provider",
            ),
        ),
        migrations.AddIndex(
            model_name="syncrun",
            index=models.Index(
                fields=["provider", "status"], name="integration_provide_860aeb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncrun",
            index=models.Index(fields=["started_at"], name="integration_started_58bc4c_idx"),
        ),
        migrations.AddIndex(
            model_name="syncissue",
            index=models.Index(
                fields=["severity", "resolved_at"], name="integration_severit_79c6ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncissue",
            index=models.Index(fields=["kind", "resolved_at"], name="integration_kind_4fdce7_idx"),
        ),
    ]
