# Generated by Django 5.2.14 on 2026-06-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syncrecord",
            name="provider",
            field=models.CharField(
                choices=[
                    ("ZOHO_CRM", "Zoho CRM"),
                    ("FLYWIRE", "Flywire"),
                    ("WORDPRESS_SITE", "WordPress site"),
                    ("LEGACY_DOTNET", "Legacy .NET"),
                    ("ICAL", "iCal feed"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="syncrun",
            name="provider",
            field=models.CharField(
                choices=[
                    ("ZOHO_CRM", "Zoho CRM"),
                    ("FLYWIRE", "Flywire"),
                    ("WORDPRESS_SITE", "WordPress site"),
                    ("LEGACY_DOTNET", "Legacy .NET"),
                    ("ICAL", "iCal feed"),
                ],
                max_length=32,
            ),
        ),
    ]
