# Generated by Django 5.2.14 on 2026-07-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationInboundCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("ZOHO_CRM", "Zoho CRM"),
                            ("FLYWIRE", "Flywire"),
                            ("WORDPRESS_SITE", "WordPress site"),
                            ("LEGACY_DOTNET", "Legacy .NET"),
                            ("ICAL", "iCal feed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("response_status", models.PositiveSmallIntegerField()),
                ("response_body", models.JSONField()),
                ("response_body_hash", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "idempotency_key"),
                        name="unique_inbound_call_per_provider_key",
                    )
                ],
            },
        ),
    ]
