# Generated by Django 5.2.14 on 2026-07-08 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("owners", "0001_initial"),
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ownerorgproperty",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_grants",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="ownerorgproperty",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="ownermembership",
            index=models.Index(fields=["user", "status"], name="ownermembership_user_status"),
        ),
        migrations.AddConstraint(
            model_name="ownermembership",
            constraint=models.UniqueConstraint(
                fields=("organisation", "user"), name="unique_membership_per_org_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="ownerorgproperty",
            constraint=models.UniqueConstraint(
                condition=models.Q(("end_date__isnull", True)),
                fields=("organisation", "property"),
                name="unique_active_org_property_grant",
            ),
        ),
    ]
