# Generated by Django 5.2.14 on 2026-07-08 11:54

import core.fields
import datetime
import django.core.validators
import django.db.models.deletion
import properties.timezones
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("pricing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("iso2", models.CharField(max_length=2, unique=True)),
                ("iso3", models.CharField(max_length=3, unique=True)),
                ("dial_code", models.CharField(blank=True, max_length=8)),
                (
                    "default_tax_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "countries",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="FeatureCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("slug", models.SlugField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=128)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "feature categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="NearbyPlaceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("icon", models.CharField(blank=True, max_length=128)),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PropertyCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("slug", models.SlugField(max_length=128, unique=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "property categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "placement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("main_house", "Main house"),
                            ("guest_house", "Guest house"),
                            ("pool_house", "Pool house"),
                            ("annex", "Annexe"),
                            ("cottage", "Cottage"),
                            ("bungalow", "Bungalow"),
                            ("studio", "Studio"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "floor",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lower_ground", "Lower ground"),
                            ("ground", "Ground"),
                            ("first", "First"),
                            ("second", "Second"),
                            ("third_plus", "Third or above"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("placement_note", models.CharField(blank=True, default="", max_length=255)),
                ("website_description", models.TextField(blank=True)),
                ("vc_notes", models.TextField(blank=True)),
                ("is_ensuite", models.BooleanField(default=False)),
                (
                    "ensuite_type",
                    models.CharField(
                        blank=True,
                        choices=[("shower", "Shower"), ("bath", "Bath"), ("both", "Bath & shower")],
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "access",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("inside", "Inside access"),
                            ("outside", "Separate outside access"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["property_id", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("slug", models.SlugField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="collections/%Y/%m/"),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CollectionMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("featured_until", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="properties.collection",
                    ),
                ),
            ],
            options={
                "ordering": ["collection_id", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("slug", models.SlugField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=128)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("amenity", "Amenity"),
                            ("included_service", "Included service"),
                            ("paid_addon", "Paid add-on"),
                        ],
                        default="amenity",
                        max_length=24,
                    ),
                ),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="features",
                        to="properties.featurecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["category_id", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("licence_number", models.CharField(blank=True, max_length=128)),
                ("video_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("direct", "Direct"),
                            ("agent", "Agent"),
                            ("white_label", "White label"),
                            ("internal", "Internal"),
                        ],
                        default="direct",
                        max_length=16,
                    ),
                ),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                ("availability_owner_updated_at", models.DateTimeField(blank=True, null=True)),
                ("availability_confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "availability_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "collections",
                    models.ManyToManyField(
                        blank=True,
                        related_name="properties",
                        through="properties.CollectionMembership",
                        to="properties.collection",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="properties",
                        to="properties.propertycategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "properties",
                "ordering": ["name", "id"],
            },
        ),
        migrations.AddField(
            model_name="collectionmembership",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_memberships",
                to="properties.property",
            ),
        ),
        migrations.CreateModel(
            name="ChangeOverRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("mon", "Monday"),
                            ("tue", "Tuesday"),
                            ("wed", "Wednesday"),
                            ("thu", "Thursday"),
                            ("fri", "Friday"),
                            ("sat", "Saturday"),
                            ("sun", "Sunday"),
                            ("any", "Any day"),
                        ],
                        max_length=8,
                    ),
                ),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changeover_rules",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["property_id", "starts_on"],
            },
        ),
        migrations.CreateModel(
            name="PropertyCalendarFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(max_length=500)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("airbnb", "Airbnb"),
                            ("vrbo", "Vrbo / HomeAway"),
                            ("booking_com", "Booking.com"),
                            ("google", "Google Calendar"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("last_polled_at", models.DateTimeField(blank=True, null=True)),
                ("last_status", models.CharField(blank=True, default="", max_length=16)),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_feeds",
                        to="properties.property",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["property_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="PropertyContactAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("manager", "Villa Manager"),
                            ("agent", "Agent"),
                            ("villa_admin", "Villa Admin"),
                            ("management_company", "Management Company"),
                            ("housekeeper", "Housekeeper"),
                            ("owners_rep", "Owner's representative"),
                        ],
                        max_length=24,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="property_assignments",
                        to="accounts.person",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="property_assignments",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_assignments",
                        to="properties.property",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["property_id", "role"],
            },
        ),
        migrations.AddField(
            model_name="property",
            name="contacts",
            field=models.ManyToManyField(
                blank=True,
                related_name="properties",
                through="properties.PropertyContactAssignment",
                to="accounts.person",
            ),
        ),
        migrations.CreateModel(
            name="PropertyDefaults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "availability_default",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("unavailable", "Unavailable"),
                            ("on_request", "On request"),
                        ],
                        default="available",
                        max_length=16,
                    ),
                ),
                ("bookings_require_pre_approval", models.BooleanField(default=False)),
                ("requires_enquiry_first", models.BooleanField(default=False)),
                (
                    "check_in_time",
                    models.TimeField(blank=True, default=datetime.time(16, 30), null=True),
                ),
                (
                    "check_out_time",
                    models.TimeField(blank=True, default=datetime.time(10, 30), null=True),
                ),
                (
                    "changeover_day",
                    models.CharField(
                        choices=[
                            ("mon", "Monday"),
                            ("tue", "Tuesday"),
                            ("wed", "Wednesday"),
                            ("thu", "Thursday"),
                            ("fri", "Friday"),
                            ("sat", "Saturday"),
                            ("sun", "Sunday"),
                            ("any", "Any day"),
                        ],
                        default="any",
                        max_length=8,
                    ),
                ),
                ("min_nights_rental", models.PositiveSmallIntegerField(default=1)),
                ("min_nights_rental_note", models.TextField(blank=True)),
                (
                    "prices_entered_as",
                    models.CharField(
                        choices=[("gross", "Gross"), ("net", "Net")], default="gross", max_length=8
                    ),
                ),
                ("hold_duration_hours", models.PositiveSmallIntegerField(default=48)),
                (
                    "commission_calculation_type",
                    models.CharField(
                        choices=[("percent", "Percent"), ("fixed", "Fixed")],
                        default="percent",
                        max_length=8,
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("commission_note", models.TextField(blank=True)),
                ("tax_is_exempt", models.BooleanField(default=False)),
                ("tax_percentage", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("deposit_required", models.BooleanField(default=True)),
                (
                    "deposit_calculation_type",
                    models.CharField(
                        choices=[("percent", "Percent"), ("fixed", "Fixed")],
                        default="percent",
                        max_length=8,
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(decimal_places=2, default=30, max_digits=12),
                ),
                ("interim_required", models.BooleanField(default=False)),
                (
                    "interim_calculation_type",
                    models.CharField(
                        choices=[("percent", "Percent"), ("fixed", "Fixed")],
                        default="percent",
                        max_length=8,
                    ),
                ),
                ("interim_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("days_interim_due_before_arrival", models.PositiveSmallIntegerField(default=0)),
                ("days_balance_due_before_arrival", models.PositiveSmallIntegerField(default=60)),
                ("security_deposit_required", models.BooleanField(default=True)),
                (
                    "security_deposit_calculation_type",
                    models.CharField(
                        choices=[("percent", "Percent"), ("fixed", "Fixed")],
                        default="fixed",
                        max_length=8,
                    ),
                ),
                (
                    "security_deposit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "security_deposit_days_due_before_arrival",
                    models.PositiveSmallIntegerField(default=14),
                ),
                (
                    "security_deposit_days_refunded_after_departure",
                    models.PositiveSmallIntegerField(default=7),
                ),
                (
                    "security_deposit_payment_method",
                    models.CharField(
                        choices=[
                            ("card_hold", "Card hold"),
                            ("card_charge", "Card charge"),
                            ("bank_transfer", "Bank transfer"),
                        ],
                        default="card_hold",
                        max_length=16,
                    ),
                ),
                (
                    "cancellation_fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cancellation_fee_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("cancellation_window_days", models.PositiveSmallIntegerField(default=0)),
                ("cancellation_notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="pricing.currency",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "property defaults",
                "verbose_name_plural": "property defaults",
            },
        ),
        migrations.CreateModel(
            name="PropertyDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("overview", "Overview"),
                            ("house_rules", "House rules"),
                            ("villa_info", "Villa info"),
                            ("further_info", "Further info"),
                            ("location", "Location"),
                            ("web_description", "Web description"),
                        ],
                        max_length=16,
                    ),
                ),
                ("body", models.TextField(blank=True)),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descriptions",
                        to="properties.property",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["property_id", "section"],
            },
        ),
        migrations.CreateModel(
            name="PropertyFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_derived", models.BooleanField(default=False)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="properties.feature",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_links",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "properties_property_features",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="property",
            name="features",
            field=models.ManyToManyField(
                blank=True,
                related_name="properties",
                through="properties.PropertyFeature",
                to="properties.feature",
            ),
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="properties/%Y/%m/")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("hero", "Hero"),
                            ("interior", "Interior"),
                            ("exterior", "Exterior"),
                            ("gallery", "Gallery"),
                            ("floor_plan", "Floor plan"),
                        ],
                        default="gallery",
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.property",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["property_id", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PropertyNearbyPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("distance_km", models.DecimalField(decimal_places=2, max_digits=6)),
                ("notes", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "place_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placements",
                        to="properties.nearbyplacetype",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nearby_places",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["property_id", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PropertyService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("copy", models.TextField()),
                ("notes", models.TextField(blank=True)),
                ("applies_from", models.DateField(blank=True, null=True)),
                ("applies_to", models.DateField(blank=True, null=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="properties.property",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["property", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("slug", models.SlugField(max_length=128)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="regions",
                        to="properties.country",
                    ),
                ),
            ],
            options={
                "ordering": ["country__name", "sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="property",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="properties",
                to="properties.region",
            ),
        ),
        migrations.CreateModel(
            name="RoomBeds",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="beds",
                        serialize=False,
                        to="properties.room",
                    ),
                ),
                ("double", models.PositiveSmallIntegerField(default=0)),
                (
                    "double_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("king", "King"),
                            ("super_king", "Super-king"),
                            ("emperor", "Emperor"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("twin_double", models.PositiveSmallIntegerField(default=0)),
                ("twin", models.PositiveSmallIntegerField(default=0)),
                ("single", models.PositiveSmallIntegerField(default=0)),
                ("bunk", models.PositiveSmallIntegerField(default=0)),
                ("sofa", models.PositiveSmallIntegerField(default=0)),
                ("childrens", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "room beds",
            },
        ),
        migrations.AddField(
            model_name="room",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="RoomAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=64)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "implies_property_feature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="properties.feature",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="RoomAttributeAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="properties.roomattribute",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_links",
                        to="properties.room",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PropertyCapacity",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="capacity",
                        serialize=False,
                        to="properties.property",
                    ),
                ),
                ("guests", models.PositiveSmallIntegerField(default=0)),
                ("additional_guests", models.PositiveSmallIntegerField(default=0)),
                ("bedrooms", models.PositiveSmallIntegerField(default=0)),
                ("ensuites", models.PositiveSmallIntegerField(default=0)),
                ("bathrooms", models.PositiveSmallIntegerField(default=0)),
                (
                    "size_sqm",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PropertyFinance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="finance",
                        serialize=False,
                        to="properties.property",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "commission_calculation_type",
                    models.CharField(
                        blank=True,
                        choices=[("percent", "Percent"), ("fixed", "Fixed")],
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("commission_note", models.TextField(blank=True)),
                ("tax_number", models.CharField(blank=True, max_length=64)),
                ("tax_is_exempt", models.BooleanField(blank=True, null=True)),
                (
                    "tax_percentage",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("bank_account_name", models.CharField(blank=True, max_length=128)),
                ("bank_account_number", core.fields.EncryptedTextField(blank=True, default="")),
                ("bank_sort_code", core.fields.EncryptedTextField(blank=True, default="")),
                ("bank_iban", core.fields.EncryptedTextField(blank=True, default="")),
                ("bank_bic", core.fields.EncryptedTextField(blank=True, default="")),
                ("bank_name", models.CharField(blank=True, max_length=128)),
                ("bank_address_line_1", models.CharField(blank=True, max_length=255)),
                ("bank_address_line_2", models.CharField(blank=True, max_length=255)),
                ("bank_post_code", models.CharField(blank=True, max_length=32)),
                ("bank_city", models.CharField(blank=True, max_length=128)),
                ("deposit_required", models.BooleanField(blank=True, null=True)),
                (
                    "deposit_calculation_type",
                    models.CharField(
                        blank=True,
                        choices=[("percent", "Percent"), ("fixed", "Fixed")],
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("interim_required", models.BooleanField(blank=True, null=True)),
                (
                    "interim_calculation_type",
                    models.CharField(
                        blank=True,
                        choices=[("percent", "Percent"), ("fixed", "Fixed")],
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "interim_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "days_interim_due_before_arrival",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "days_balance_due_before_arrival",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("security_deposit_required", models.BooleanField(blank=True, null=True)),
                (
                    "security_deposit_calculation_type",
                    models.CharField(
                        blank=True,
                        choices=[("percent", "Percent"), ("fixed", "Fixed")],
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "security_deposit_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "security_deposit_days_due_before_arrival",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "security_deposit_days_refunded_after_departure",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "security_deposit_payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("card_hold", "Card hold"),
                            ("card_charge", "Card charge"),
                            ("bank_transfer", "Bank transfer"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "cancellation_fee_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "cancellation_fee_percent",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "cancellation_window_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("cancellation_notes", models.TextField(blank=True)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.person",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="properties.propertyfinance",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pricing.rateplan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PropertyLocation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="location",
                        serialize=False,
                        to="properties.property",
                    ),
                ),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("address_line_3", models.CharField(blank=True, max_length=255)),
                ("post_code", models.CharField(blank=True, max_length=32)),
                ("locality_town", models.CharField(blank=True, max_length=128)),
                ("locality_region", models.CharField(blank=True, max_length=128)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        max_length=64,
                        validators=[properties.timezones.validate_iana_timezone],
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="property_locations",
                        to="properties.country",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PropertySettings",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="settings",
                        serialize=False,
                        to="properties.property",
                    ),
                ),
                (
                    "availability_default",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("available", "Available"),
                            ("unavailable", "Unavailable"),
                            ("on_request", "On request"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("bookings_require_pre_approval", models.BooleanField(blank=True, null=True)),
                ("requires_enquiry_first", models.BooleanField(blank=True, null=True)),
                ("check_in_time", models.TimeField(blank=True, null=True)),
                ("check_out_time", models.TimeField(blank=True, null=True)),
                (
                    "changeover_day",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mon", "Monday"),
                            ("tue", "Tuesday"),
                            ("wed", "Wednesday"),
                            ("thu", "Thursday"),
                            ("fri", "Friday"),
                            ("sat", "Saturday"),
                            ("sun", "Sunday"),
                            ("any", "Any day"),
                        ],
                        max_length=8,
                        null=True,
                    ),
                ),
                ("min_nights_rental", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("min_nights_rental_note", models.TextField(blank=True, null=True)),
                (
                    "prices_entered_as",
                    models.CharField(
                        blank=True,
                        choices=[("gross", "Gross"), ("net", "Net")],
                        max_length=8,
                        null=True,
                    ),
                ),
                ("hold_duration_hours", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("calendar_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="pricing.currency",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="collectionmembership",
            constraint=models.UniqueConstraint(
                fields=("collection", "property"), name="unique_collection_property"
            ),
        ),
        migrations.AddConstraint(
            model_name="changeoverrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_on__gte", models.F("starts_on"))),
                name="changeover_rule_ends_on_or_after_starts_on",
            ),
        ),
        migrations.AddIndex(
            model_name="propertycalendarfeed",
            index=models.Index(
                fields=["property", "is_active"], name="properties__propert_6c1d70_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="propertycalendarfeed",
            constraint=models.UniqueConstraint(
                fields=("property", "url"), name="unique_calendar_feed_url_per_property"
            ),
        ),
        migrations.AddConstraint(
            model_name="propertycontactassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("end_date__isnull", True)),
                fields=("property", "contact", "role"),
                name="unique_active_role_assignment",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertycontactassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("end_date__isnull", True)),
                fields=("property", "organisation", "role"),
                name="unique_active_role_org_assignment",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertycontactassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("end_date__isnull", True), ("is_primary", True)),
                fields=("property", "role"),
                name="one_primary_per_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertycontactassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("contact__isnull", False), ("organisation__isnull", True)),
                    models.Q(("contact__isnull", True), ("organisation__isnull", False)),
                    _connector="OR",
                ),
                name="assignment_contact_xor_organisation",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertycontactassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("organisation__isnull", True), ("role", "management_company"), _connector="OR"
                ),
                name="org_assignee_only_management_company",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertydescription",
            constraint=models.UniqueConstraint(
                fields=("property", "section"), name="one_description_per_section"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="propertyfeature",
            unique_together={("property", "feature")},
        ),
        migrations.AddConstraint(
            model_name="propertyimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("kind", "hero")),
                fields=("property",),
                name="unique_active_hero_per_property",
            ),
        ),
        migrations.AddIndex(
            model_name="propertyservice",
            index=models.Index(
                fields=["property", "is_active", "sort_order"],
                name="properties__propert_e7c98a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertyservice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("applies_from__isnull", True),
                    ("applies_to__isnull", True),
                    ("applies_from__lte", models.F("applies_to")),
                    _connector="OR",
                ),
                name="propertyservice_applies_from_lte_applies_to",
            ),
        ),
        migrations.AddConstraint(
            model_name="region",
            constraint=models.UniqueConstraint(
                fields=("country", "slug"), name="unique_region_slug_per_country"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["status"], name="properties__status_6427a0_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["region", "status"], name="properties__region__925dbb_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["legacy_id"], name="properties__legacy__4bcd75_idx"),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.CheckConstraint(
                condition=models.Q(("ensuite_type", ""), ("is_ensuite", True), _connector="OR"),
                name="room_ensuite_type_implies_is_ensuite",
            ),
        ),
        migrations.AddConstraint(
            model_name="roomattributeassignment",
            constraint=models.UniqueConstraint(
                fields=("room", "attribute"), name="unique_room_attribute"
            ),
        ),
    ]
