# Generated by Django 5.2.14 on 2026-05-12 22:02

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_contact_contactemail_contactphone_usersession_and_more"),
        ("pricing", "0003_raterule_exclude_constraint"),
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupFinance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="finance",
                        serialize=False,
                        to="properties.propertygroup",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "commission_calculation_type",
                    models.CharField(
                        choices=[("percent", "Percent"), ("fixed", "Fixed")],
                        default="percent",
                        max_length=8,
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("commission_note", models.TextField(blank=True)),
                ("tax_number", models.CharField(blank=True, max_length=64)),
                ("tax_is_exempt", models.BooleanField(default=False)),
                ("tax_percentage", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("bank_account_name", models.CharField(blank=True, max_length=128)),
                ("bank_account_number", core.fields.EncryptedTextField(blank=True, default="")),
                ("bank_sort_code", core.fields.EncryptedTextField(blank=True, default="")),
                ("bank_iban", core.fields.EncryptedTextField(blank=True, default="")),
                ("bank_bic", core.fields.EncryptedTextField(blank=True, default="")),
                ("bank_name", models.CharField(blank=True, max_length=128)),
                ("bank_address_line_1", models.CharField(blank=True, max_length=255)),
                ("bank_address_line_2", models.CharField(blank=True, max_length=255)),
                ("bank_post_code", models.CharField(blank=True, max_length=32)),
                ("bank_city", models.CharField(blank=True, max_length=128)),
                ("deposit_required", models.BooleanField(default=True)),
                (
                    "deposit_calculation_type",
                    models.CharField(
                        choices=[("percent", "Percent"), ("fixed", "Fixed")],
                        default="percent",
                        max_length=8,
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(decimal_places=2, default=30, max_digits=12),
                ),
                ("interim_required", models.BooleanField(default=False)),
                (
                    "interim_calculation_type",
                    models.CharField(
                        choices=[("percent", "Percent"), ("fixed", "Fixed")],
                        default="percent",
                        max_length=8,
                    ),
                ),
                ("interim_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("days_interim_due_before_arrival", models.PositiveSmallIntegerField(default=0)),
                ("days_balance_due_before_arrival", models.PositiveSmallIntegerField(default=60)),
                ("security_deposit_required", models.BooleanField(default=False)),
                (
                    "security_deposit_calculation_type",
                    models.CharField(
                        choices=[("percent", "Percent"), ("fixed", "Fixed")],
                        default="fixed",
                        max_length=8,
                    ),
                ),
                (
                    "security_deposit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "security_deposit_calculate_from",
                    models.CharField(
                        choices=[
                            ("nightly", "Nightly"),
                            ("weekly", "Weekly"),
                            ("total_stay", "Total stay"),
                        ],
                        default="total_stay",
                        max_length=16,
                    ),
                ),
                (
                    "security_deposit_days_due_before_arrival",
                    models.PositiveSmallIntegerField(default=14),
                ),
                (
                    "security_deposit_days_refunded_after_departure",
                    models.PositiveSmallIntegerField(default=7),
                ),
                (
                    "security_deposit_payment_method",
                    models.CharField(
                        choices=[
                            ("card_hold", "Card hold (pre-auth)"),
                            ("card_charge", "Card charge"),
                            ("bank_transfer", "Bank transfer"),
                        ],
                        default="card_hold",
                        max_length=16,
                    ),
                ),
                (
                    "cancellation_fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cancellation_fee_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("cancellation_window_days", models.PositiveSmallIntegerField(default=0)),
                ("cancellation_notes", models.TextField(blank=True)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.contact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="pricing.currency",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PropertyFinance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="finance",
                        serialize=False,
                        to="properties.property",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "commission_calculation_type",
                    models.CharField(
                        blank=True,
                        choices=[("percent", "Percent"), ("fixed", "Fixed")],
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("commission_note", models.TextField(blank=True)),
                ("tax_number", models.CharField(blank=True, max_length=64)),
                ("tax_is_exempt", models.BooleanField(blank=True, null=True)),
                (
                    "tax_percentage",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("bank_account_name", models.CharField(blank=True, max_length=128)),
                ("bank_account_number", core.fields.EncryptedTextField(blank=True, default="")),
                ("bank_sort_code", core.fields.EncryptedTextField(blank=True, default="")),
                ("bank_iban", core.fields.EncryptedTextField(blank=True, default="")),
                ("bank_bic", core.fields.EncryptedTextField(blank=True, default="")),
                ("bank_name", models.CharField(blank=True, max_length=128)),
                ("bank_address_line_1", models.CharField(blank=True, max_length=255)),
                ("bank_address_line_2", models.CharField(blank=True, max_length=255)),
                ("bank_post_code", models.CharField(blank=True, max_length=32)),
                ("bank_city", models.CharField(blank=True, max_length=128)),
                ("deposit_required", models.BooleanField(blank=True, null=True)),
                (
                    "deposit_calculation_type",
                    models.CharField(
                        blank=True,
                        choices=[("percent", "Percent"), ("fixed", "Fixed")],
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("interim_required", models.BooleanField(blank=True, null=True)),
                (
                    "interim_calculation_type",
                    models.CharField(
                        blank=True,
                        choices=[("percent", "Percent"), ("fixed", "Fixed")],
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "interim_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "days_interim_due_before_arrival",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "days_balance_due_before_arrival",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("security_deposit_required", models.BooleanField(blank=True, null=True)),
                (
                    "security_deposit_calculation_type",
                    models.CharField(
                        blank=True,
                        choices=[("percent", "Percent"), ("fixed", "Fixed")],
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "security_deposit_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "security_deposit_calculate_from",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nightly", "Nightly"),
                            ("weekly", "Weekly"),
                            ("total_stay", "Total stay"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "security_deposit_days_due_before_arrival",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "security_deposit_days_refunded_after_departure",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "security_deposit_payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("card_hold", "Card hold (pre-auth)"),
                            ("card_charge", "Card charge"),
                            ("bank_transfer", "Bank transfer"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "cancellation_fee_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "cancellation_fee_percent",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "cancellation_window_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("cancellation_notes", models.TextField(blank=True)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.contact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="properties.propertyfinance",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pricing.rateplan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
