# Generated by Django 5.2.14 on 2026-05-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0002_groupfinance_propertyfinance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupfinance",
            name="security_deposit_payment_method",
            field=models.CharField(
                choices=[
                    ("card_hold", "Card hold"),
                    ("card_charge", "Card charge"),
                    ("bank_transfer", "Bank transfer"),
                ],
                default="card_hold",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="propertyfinance",
            name="security_deposit_payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("card_hold", "Card hold"),
                    ("card_charge", "Card charge"),
                    ("bank_transfer", "Bank transfer"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
