# Generated by Django 5.2.14 on 2026-07-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0003_seed_room_attributes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertydefaults",
            name="prices_entered_as",
            field=models.CharField(
                choices=[("gross", "Gross"), ("net", "Net")],
                default="gross",
                help_text="Entry-form pre-fill for new rate plans; the engine prices from RatePlan.price_basis.",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="propertysettings",
            name="prices_entered_as",
            field=models.CharField(
                blank=True,
                choices=[("gross", "Gross"), ("net", "Net")],
                help_text="Entry-form pre-fill for new rate plans; the engine prices from RatePlan.price_basis.",
                max_length=8,
                null=True,
            ),
        ),
    ]
