# Generated by Django 5.2.14 on 2026-05-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0003_alter_groupfinance_security_deposit_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="legacy_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
