# Generated by Django 5.2.14 on 2026-08-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0004_alter_propertydefaults_prices_entered_as_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertydescription",
            name="section",
            field=models.CharField(
                choices=[
                    ("overview", "Overview"),
                    ("house_rules", "House rules"),
                    ("villa_info", "Villa info"),
                    ("further_info", "Further info"),
                    ("location", "Location"),
                    ("web_description", "Web description"),
                    ("internal_notes", "Internal notes"),
                ],
                max_length=16,
            ),
        ),
    ]
