# Generated by Django 5.2.14 on 2026-09-01 19:08
#
# GAP-093 — drop `Property.category` and the `PropertyCategory` lookup.
# Country + region is enough (owner call, 2026-07-20).
#
# Deliberately one-way (unlike GAP-070's property-group removal, which
# hand-ordered SeparateDatabaseAndState + reverse_sql to stay reversible):
# `category_id` was NOT NULL with no default, so reversing this on a
# populated table fails. No MigrationExecutor rollback guard tests remain
# post-flatten (2026-07-08), so nothing pins reversibility. Restore from
# backup instead.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0005_alter_propertydescription_section"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="category",
        ),
        migrations.DeleteModel(
            name="PropertyCategory",
        ),
    ]
