# Generated by Django 5.2.14 on 2026-05-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0005_collection_legacy_id_feature_legacy_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionmembership",
            name="legacy_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
