# Generated by Django 5.2.14 on 2026-05-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0006_collectionmembership_legacy_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyimage",
            name="legacy_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="propertynearbyplace",
            name="legacy_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="legacy_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
