# Generated by Django 5.2.14 on 2026-05-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0007_propertyimage_legacy_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertycontactassignment",
            name="legacy_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
