# Generated by Django 5.2.14 on 2026-05-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0010_drop_dev_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupsettings",
            name="hold_duration_hours",
            field=models.PositiveSmallIntegerField(default=48),
        ),
        migrations.AddField(
            model_name="propertysettings",
            name="hold_duration_hours",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
