# Generated by Django 5.2.14 on 2026-06-04 12:36

import properties.timezones
from django.db import migrations, models

# Inlined copy of properties.timezones.COUNTRY_TIMEZONES — a data migration must
# not import mutable app code (it would break if the map later changes shape).
# Keep in sync with properties/timezones.py.
_COUNTRY_TIMEZONES = {
    "GB": "Europe/London",
    "FR": "Europe/Paris",
    "ES": "Europe/Madrid",
    "IT": "Europe/Rome",
    "GR": "Europe/Athens",
    "PT": "Europe/Lisbon",
    "CH": "Europe/Zurich",
    "BB": "America/Barbados",
    "BL": "America/St_Barthelemy",
    "ID": "Asia/Makassar",
    "TH": "Asia/Bangkok",
    "MX": "America/Cancun",
}


def backfill_timezone_from_country(apps, schema_editor):
    Location = apps.get_model("properties", "PropertyLocation")
    for iso2, tz in _COUNTRY_TIMEZONES.items():
        Location.objects.filter(country__iso2=iso2).update(timezone=tz)
    # Rows in any other country keep the UTC default; ops corrects outliers.


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0012_backfill_feature_icons"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertylocation",
            name="timezone",
            field=models.CharField(
                default="UTC",
                max_length=64,
                validators=[properties.timezones.validate_iana_timezone],
            ),
        ),
        migrations.RunPython(
            backfill_timezone_from_country,
            migrations.RunPython.noop,
        ),
    ]
