# Generated by Django 5.2.14 on 2026-06-09 17:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0015_alter_propertylocation_latitude_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={"ordering": ["name", "id"], "verbose_name_plural": "properties"},
        ),
    ]
