# Generated by Django 5.2.14 on 2026-06-18 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_rename_person_status_index"),
        ("properties", "0016_alter_property_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupfinance",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounts.person",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="contacts",
            field=models.ManyToManyField(
                blank=True,
                related_name="properties",
                through="properties.PropertyContactAssignment",
                to="accounts.person",
            ),
        ),
        migrations.AlterField(
            model_name="propertycontactassignment",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="property_assignments",
                to="accounts.person",
            ),
        ),
        migrations.AlterField(
            model_name="propertyfinance",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounts.person",
            ),
        ),
    ]
