# Generated by Django 5.2.14 on 2026-06-18 07:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0017_alter_groupfinance_contact_alter_property_contacts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupfinance",
            name="security_deposit_calculate_from",
        ),
        migrations.RemoveField(
            model_name="propertyfinance",
            name="security_deposit_calculate_from",
        ),
    ]
