# Generated by Django 5.2.14 on 2026-06-18 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0018_propertyfeature_related_name"),
        ("properties", "0018_remove_groupfinance_security_deposit_calculate_from_and_more"),
    ]

    operations = []
