# Generated by Django 5.2.14 on 2026-06-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0019_merge_20260618_1201"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertysettings",
            name="calendar_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
