# Generated by Django 5.2.14 on 2026-06-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0020_propertysettings_calendar_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertycontactassignment",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("manager", "Villa Manager"),
                    ("agent", "Agent"),
                    ("villa_admin", "Villa Admin"),
                    ("management_company", "Management Company"),
                    ("housekeeper", "Housekeeper"),
                    ("owners_rep", "Owner's representative"),
                ],
                max_length=24,
            ),
        ),
    ]
