# Generated by Django 5.2.14 on 2026-06-30 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_personrelationship"),
        ("properties", "0021_reconcile_contact_role_choices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="propertycontactassignment",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="property_assignments",
                to="accounts.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="propertycontactassignment",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="property_assignments",
                to="accounts.person",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertycontactassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("end_date__isnull", True)),
                fields=("property", "organisation", "role"),
                name="unique_active_role_org_assignment",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertycontactassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("contact__isnull", False), ("organisation__isnull", True)),
                    models.Q(("contact__isnull", True), ("organisation__isnull", False)),
                    _connector="OR",
                ),
                name="assignment_contact_xor_organisation",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertycontactassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("organisation__isnull", True), ("role", "management_company"), _connector="OR"
                ),
                name="org_assignee_only_management_company",
            ),
        ),
    ]
