# Generated by Django 5.2.14 on 2026-07-01 00:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0021_property_availability_confirmed_at_and_more"),
        ("properties", "0022_propertycontactassignment_organisation_and_more"),
    ]

    operations = []
