# Generated by Django 5.2.14 on 2026-07-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0024_propertyservice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertysettings",
            name="min_nights_rental_note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
