# Generated by Django 5.2.14 on 2026-07-05 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0025_alter_propertysettings_min_nights_rental_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=64)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="RoomAttributeAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="room",
            name="access",
            field=models.CharField(
                blank=True,
                choices=[("inside", "Inside access"), ("outside", "Separate outside access")],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="ensuite_type",
            field=models.CharField(
                blank=True,
                choices=[("shower", "Shower"), ("bath", "Bath"), ("both", "Bath & shower")],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.CheckConstraint(
                condition=models.Q(("ensuite_type", ""), ("is_ensuite", True), _connector="OR"),
                name="room_ensuite_type_implies_is_ensuite",
            ),
        ),
        migrations.AddField(
            model_name="roomattribute",
            name="implies_property_feature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="properties.feature",
            ),
        ),
        migrations.AddField(
            model_name="roomattributeassignment",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="properties.roomattribute",
            ),
        ),
        migrations.AddField(
            model_name="roomattributeassignment",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attribute_links",
                to="properties.room",
            ),
        ),
        migrations.AddConstraint(
            model_name="roomattributeassignment",
            constraint=models.UniqueConstraint(
                fields=("room", "attribute"), name="unique_room_attribute"
            ),
        ),
    ]
