# Generated by Django 5.2.14 on 2026-07-05 07:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_singleton(apps, schema_editor):
    """Create the pk=1 row (GAP-068 confirmed starter set = the field defaults)."""
    PropertyDefaults = apps.get_model("properties", "PropertyDefaults")
    PropertyDefaults.objects.get_or_create(pk=1)


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0018_rateplan_prices_by_occupancy"),
        ("properties", "0025_alter_propertysettings_min_nights_rental_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyDefaults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "availability_default",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("unavailable", "Unavailable"),
                            ("on_request", "On request"),
                        ],
                        default="available",
                        max_length=16,
                    ),
                ),
                ("bookings_require_pre_approval", models.BooleanField(default=False)),
                ("requires_enquiry_first", models.BooleanField(default=False)),
                (
                    "check_in_time",
                    models.TimeField(blank=True, default=datetime.time(16, 30), null=True),
                ),
                (
                    "check_out_time",
                    models.TimeField(blank=True, default=datetime.time(10, 30), null=True),
                ),
                (
                    "changeover_day",
                    models.CharField(
                        choices=[
                            ("mon", "Monday"),
                            ("tue", "Tuesday"),
                            ("wed", "Wednesday"),
                            ("thu", "Thursday"),
                            ("fri", "Friday"),
                            ("sat", "Saturday"),
                            ("sun", "Sunday"),
                            ("any", "Any day"),
                        ],
                        default="any",
                        max_length=8,
                    ),
                ),
                ("min_nights_rental", models.PositiveSmallIntegerField(default=1)),
                ("min_nights_rental_note", models.TextField(blank=True)),
                (
                    "prices_entered_as",
                    models.CharField(
                        choices=[("gross", "Gross"), ("net", "Net")], default="gross", max_length=8
                    ),
                ),
                ("hold_duration_hours", models.PositiveSmallIntegerField(default=48)),
                (
                    "commission_calculation_type",
                    models.CharField(
                        choices=[("percent", "Percent"), ("fixed", "Fixed")],
                        default="percent",
                        max_length=8,
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("commission_note", models.TextField(blank=True)),
                ("tax_is_exempt", models.BooleanField(default=False)),
                ("tax_percentage", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("deposit_required", models.BooleanField(default=True)),
                (
                    "deposit_calculation_type",
                    models.CharField(
                        choices=[("percent", "Percent"), ("fixed", "Fixed")],
                        default="percent",
                        max_length=8,
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(decimal_places=2, default=30, max_digits=12),
                ),
                ("interim_required", models.BooleanField(default=False)),
                (
                    "interim_calculation_type",
                    models.CharField(
                        choices=[("percent", "Percent"), ("fixed", "Fixed")],
                        default="percent",
                        max_length=8,
                    ),
                ),
                ("interim_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("days_interim_due_before_arrival", models.PositiveSmallIntegerField(default=0)),
                ("days_balance_due_before_arrival", models.PositiveSmallIntegerField(default=60)),
                ("security_deposit_required", models.BooleanField(default=True)),
                (
                    "security_deposit_calculation_type",
                    models.CharField(
                        choices=[("percent", "Percent"), ("fixed", "Fixed")],
                        default="fixed",
                        max_length=8,
                    ),
                ),
                (
                    "security_deposit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "security_deposit_days_due_before_arrival",
                    models.PositiveSmallIntegerField(default=14),
                ),
                (
                    "security_deposit_days_refunded_after_departure",
                    models.PositiveSmallIntegerField(default=7),
                ),
                (
                    "security_deposit_payment_method",
                    models.CharField(
                        choices=[
                            ("card_hold", "Card hold"),
                            ("card_charge", "Card charge"),
                            ("bank_transfer", "Bank transfer"),
                        ],
                        default="card_hold",
                        max_length=16,
                    ),
                ),
                (
                    "cancellation_fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cancellation_fee_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("cancellation_window_days", models.PositiveSmallIntegerField(default=0)),
                ("cancellation_notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="pricing.currency",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "property defaults",
                "verbose_name_plural": "property defaults",
            },
        ),
        migrations.RunPython(seed_singleton, migrations.RunPython.noop),
    ]
