# Generated by Django 5.2.14 on 2026-07-05 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0026_dedupe_factory_regions"),
        ("properties", "0027_seed_room_attributes"),
    ]

    operations = []
