# Generated by Django 5.2.14 on 2026-07-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0028_merge_20260705_1248"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="floor",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lower_ground", "Lower ground"),
                    ("ground", "Ground"),
                    ("first", "First"),
                    ("second", "Second"),
                    ("third_plus", "Third or above"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="placement_note",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="room",
            name="placement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("main_house", "Main house"),
                    ("guest_house", "Guest house"),
                    ("pool_house", "Pool house"),
                    ("annex", "Annexe"),
                    ("cottage", "Cottage"),
                    ("bungalow", "Bungalow"),
                    ("studio", "Studio"),
                    ("other", "Other"),
                ],
                default="",
                max_length=16,
            ),
        ),
    ]
