# Generated by Django 5.2.14 on 2026-07-06 03:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0028_remove_groupfinance_contact_and_more"),
        ("properties", "0029_room_floor_room_placement_note_alter_room_placement"),
    ]

    operations = []
