# Generated by Django 5.2.14 on 2026-07-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0030_merge_20260706_0353"),
    ]

    operations = [
        migrations.AddField(
            model_name="roombeds",
            name="double_size",
            field=models.CharField(
                blank=True,
                choices=[("king", "King"), ("super_king", "Super-king"), ("emperor", "Emperor")],
                default="",
                max_length=16,
            ),
        ),
    ]
