# Generated by Django 5.2.14 on 2026-07-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0031_roombeds_double_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyfeature",
            name="is_derived",
            field=models.BooleanField(default=False),
        ),
    ]
