# Generated by Django 5.2.14 on 2026-07-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0032_propertyfeature_is_derived"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="video_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="propertydescription",
            name="section",
            field=models.CharField(
                choices=[
                    ("overview", "Overview"),
                    ("house_rules", "House rules"),
                    ("villa_info", "Villa info"),
                    ("further_info", "Further info"),
                    ("location", "Location"),
                    ("web_description", "Web description"),
                ],
                max_length=16,
            ),
        ),
    ]
