# Generated by Django 5.2.14 on 2026-05-12 22:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pricing", "0003_raterule_exclude_constraint"),
        ("reservations", "0002_postgres_exclude_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=32, unique=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("balance", "Balance"),
                            ("security_deposit", "Security deposit"),
                            ("concierge", "Concierge"),
                            ("refund", "Refund"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("waived", "Waived"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("flywire", "Flywire"),
                            ("manual_bank_transfer", "Manual bank transfer"),
                            ("stripe", "Stripe"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("provider_reference", models.CharField(blank=True, max_length=128)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("card", "Card"),
                            ("bank_transfer", "Bank transfer"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("token", models.CharField(blank=True, max_length=128)),
                ("signature", models.CharField(blank=True, max_length=256)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("requested_at", models.DateTimeField(blank=True, null=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="reservations.booking",
                    ),
                ),
                (
                    "concierge_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="reservations.bookingconciergeitem",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="pricing.currency",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("waive_payment", "Can waive a scheduled payment"),
                    ("mark_paid_payment", "Can mark a payment as manually paid"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SecurityDeposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=32, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("pre_auth_hold", "Pre-auth hold"),
                            ("bt_refundable", "Bank-transfer refundable"),
                        ],
                        max_length=24,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting_details", "Awaiting details"),
                            ("pre_authed", "Pre-authed"),
                            ("released", "Released"),
                            ("captured", "Captured"),
                            ("expired", "Expired"),
                            ("failed", "Failed"),
                            ("awaiting_bt", "Awaiting bank transfer"),
                            ("held", "Held"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially refunded"),
                        ],
                        max_length=24,
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("hold_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "release_after_departure_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("release_scheduled_for", models.DateField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "captured_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "refunded_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("damage_claim_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("requested_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="security_deposits",
                        to="reservations.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="pricing.currency",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_deposits_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("release_securitydeposit", "Can release a security deposit"),
                    ("claim_securitydeposit", "Can claim against a security deposit"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=32, unique=True)),
                (
                    "purpose_track",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("balance", "Balance"),
                            ("security_deposit", "Security deposit"),
                            ("adjustment", "Adjustment"),
                            ("goodwill", "Goodwill"),
                        ],
                        max_length=24,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("executing", "Executing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("cancellation", "Cancellation"),
                            ("overpayment", "Overpayment"),
                            ("goodwill", "Goodwill"),
                            ("security_deposit_release", "Security deposit release"),
                            ("duplicate_charge", "Duplicate charge"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reason_notes", models.TextField(blank=True)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("online_gateway", "Online gateway"),
                            ("manual_bank_transfer", "Manual bank transfer"),
                            ("offline", "Offline"),
                        ],
                        default="online_gateway",
                        max_length=24,
                    ),
                ),
                ("requested_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "against_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds_against",
                        to="payments.payment",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="reservations.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="pricing.currency",
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds_executed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds_rejected",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "security_deposit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds",
                        to="payments.securitydeposit",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("approve_refund", "Can approve a refund"),
                    ("execute_refund", "Can execute a refund"),
                    ("self_approve_refund", "Can self-approve or self-execute a refund"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("flywire", "Flywire"), ("stripe", "Stripe")], max_length=24
                    ),
                ),
                ("event_id", models.CharField(max_length=128)),
                ("signature", models.CharField(blank=True, max_length=256)),
                ("signature_valid", models.BooleanField(default=False)),
                ("raw_body", models.TextField()),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("processing_error", models.TextField(blank=True)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_deliveries",
                        to="payments.payment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_status", models.CharField(blank=True, max_length=32)),
                ("to_status", models.CharField(blank=True, max_length=32)),
                ("kind", models.CharField(blank=True, max_length=32)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("webhook", "Webhook"),
                            ("admin", "Admin"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=16,
                    ),
                ),
                ("payload_hash", models.CharField(blank=True, max_length=128)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_events",
                        to="payments.payment",
                    ),
                ),
                (
                    "refund",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_events",
                        to="payments.refund",
                    ),
                ),
                (
                    "security_deposit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="security_deposit_events",
                        to="payments.securitydeposit",
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="payments.webhookdelivery",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["booking", "purpose"], name="payments_pa_booking_fb08f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status", "due_at"], name="payments_pa_status_a24582_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["provider_reference"], name="payments_pa_provide_48cfd7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ("pending", "processing", "succeeded")),
                    ("purpose__in", ["deposit", "balance"]),
                ),
                fields=("booking", "purpose"),
                name="unique_active_payment_per_purpose",
            ),
        ),
        migrations.AddIndex(
            model_name="securitydeposit",
            index=models.Index(fields=["booking", "status"], name="payments_se_booking_666b5f_idx"),
        ),
        migrations.AddIndex(
            model_name="securitydeposit",
            index=models.Index(
                fields=["status", "release_scheduled_for"], name="payments_se_status_92bad3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitydeposit",
            index=models.Index(
                fields=["status", "hold_expires_at"], name="payments_se_status_99d02b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="securitydeposit",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="securitydeposit_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="securitydeposit",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "released",
                            "captured",
                            "expired",
                            "failed",
                            "refunded",
                            "partially_refunded",
                        ],
                    ),
                    _negated=True,
                ),
                fields=("booking",),
                name="one_active_security_deposit_per_booking",
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(fields=["booking", "status"], name="payments_re_booking_0e2e74_idx"),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(
                fields=["status", "requested_at"], name="payments_re_status_0cd2b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(fields=["against_payment"], name="payments_re_against_cb8af6_idx"),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="refund_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approved_by__isnull", True),
                    models.Q(("approved_by", models.F("requested_by")), _negated=True),
                    _connector="OR",
                ),
                name="refund_separation_of_duties",
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["provider", "received_at"], name="payments_we_provide_36ad95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["signature_valid", "processed_at"], name="payments_we_signatu_139132_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="webhookdelivery",
            constraint=models.UniqueConstraint(
                fields=("provider", "event_id"), name="webhookdelivery_unique_provider_event_id"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentevent",
            index=models.Index(
                fields=["payment", "created_at"], name="payments_pa_payment_ec2b3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentevent",
            index=models.Index(
                fields=["refund", "created_at"], name="payments_pa_refund__55468c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentevent",
            index=models.Index(
                fields=["security_deposit", "created_at"], name="payments_pa_securit_a531eb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("payment__isnull", False),
                        ("refund__isnull", True),
                        ("security_deposit__isnull", True),
                    ),
                    models.Q(
                        ("payment__isnull", True),
                        ("refund__isnull", False),
                        ("security_deposit__isnull", True),
                    ),
                    models.Q(
                        ("payment__isnull", True),
                        ("refund__isnull", True),
                        ("security_deposit__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="paymentevent_exactly_one_target",
            ),
        ),
    ]
