# Generated by Django 5.2.14 on 2026-07-08 11:54

import django.db.models.functions.comparison
import django.db.models.functions.datetime
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        # Hand-added: the payment/refund/security-deposit reference columns
        # below carry a `DEFAULT nextval(...)`, so the sequences must exist.
        ("core", "0003_reference_sequences"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        db_default=django.db.models.functions.text.Concat(
                            models.Value("P-"),
                            django.db.models.functions.comparison.Cast(
                                django.db.models.functions.datetime.ExtractYear(
                                    django.db.models.functions.datetime.Now()
                                ),
                                output_field=models.CharField(),
                            ),
                            models.Value("-"),
                            django.db.models.functions.comparison.Cast(
                                models.Func(
                                    models.Value("payment_reference_seq"),
                                    function="nextval",
                                    output_field=models.BigIntegerField(),
                                ),
                                output_field=models.CharField(),
                            ),
                            output_field=models.CharField(),
                        ),
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("balance", "Balance"),
                            ("security_deposit", "Security deposit"),
                            ("concierge", "Concierge"),
                            ("refund", "Refund"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("waived", "Waived"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("flywire", "Flywire"),
                            ("manual_bank_transfer", "Manual bank transfer"),
                            ("stripe", "Stripe"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("provider_reference", models.CharField(blank=True, max_length=128)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("card", "Card"),
                            ("bank_transfer", "Bank transfer"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("token", models.CharField(blank=True, max_length=128)),
                ("signature", models.CharField(blank=True, max_length=256)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("requested_at", models.DateTimeField(blank=True, null=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
            ],
            options={
                "permissions": [
                    ("waive_payment", "Can waive a scheduled payment"),
                    ("mark_paid_payment", "Can mark a payment as manually paid"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_status", models.CharField(blank=True, max_length=32)),
                ("to_status", models.CharField(blank=True, max_length=32)),
                ("kind", models.CharField(blank=True, max_length=32)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("webhook", "Webhook"),
                            ("admin", "Admin"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=16,
                    ),
                ),
                ("payload_hash", models.CharField(blank=True, max_length=128)),
                ("meta", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        db_default=django.db.models.functions.text.Concat(
                            models.Value("R-"),
                            django.db.models.functions.comparison.Cast(
                                django.db.models.functions.datetime.ExtractYear(
                                    django.db.models.functions.datetime.Now()
                                ),
                                output_field=models.CharField(),
                            ),
                            models.Value("-"),
                            django.db.models.functions.comparison.Cast(
                                models.Func(
                                    models.Value("refund_reference_seq"),
                                    function="nextval",
                                    output_field=models.BigIntegerField(),
                                ),
                                output_field=models.CharField(),
                            ),
                            output_field=models.CharField(),
                        ),
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "purpose_track",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("balance", "Balance"),
                            ("security_deposit", "Security deposit"),
                            ("adjustment", "Adjustment"),
                            ("goodwill", "Goodwill"),
                        ],
                        max_length=24,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("executing", "Executing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("cancellation", "Cancellation"),
                            ("overpayment", "Overpayment"),
                            ("goodwill", "Goodwill"),
                            ("security_deposit_release", "Security deposit release"),
                            ("duplicate_charge", "Duplicate charge"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reason_notes", models.TextField(blank=True)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("online_gateway", "Online gateway"),
                            ("manual_bank_transfer", "Manual bank transfer"),
                            ("offline", "Offline"),
                        ],
                        default="online_gateway",
                        max_length=24,
                    ),
                ),
                ("requested_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("meta", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "permissions": [
                    ("approve_refund", "Can approve a refund"),
                    ("execute_refund", "Can execute a refund"),
                    ("self_approve_refund", "Can self-approve or self-execute a refund"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityDeposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        db_default=django.db.models.functions.text.Concat(
                            models.Value("SD-"),
                            django.db.models.functions.comparison.Cast(
                                django.db.models.functions.datetime.ExtractYear(
                                    django.db.models.functions.datetime.Now()
                                ),
                                output_field=models.CharField(),
                            ),
                            models.Value("-"),
                            django.db.models.functions.comparison.Cast(
                                models.Func(
                                    models.Value("security_deposit_reference_seq"),
                                    function="nextval",
                                    output_field=models.BigIntegerField(),
                                ),
                                output_field=models.CharField(),
                            ),
                            output_field=models.CharField(),
                        ),
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("pre_auth_hold", "Pre-auth hold"),
                            ("bt_refundable", "Bank-transfer refundable"),
                        ],
                        max_length=24,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting_details", "Awaiting details"),
                            ("pre_authed", "Pre-authed"),
                            ("released", "Released"),
                            ("captured", "Captured"),
                            ("expired", "Expired"),
                            ("failed", "Failed"),
                            ("awaiting_bt", "Awaiting bank transfer"),
                            ("held", "Held"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially refunded"),
                        ],
                        max_length=24,
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("hold_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "release_after_departure_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("release_scheduled_for", models.DateField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "captured_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "refunded_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("requested_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("meta", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "permissions": [
                    ("release_securitydeposit", "Can release a security deposit"),
                    ("claim_securitydeposit", "Can claim against a security deposit"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("flywire", "Flywire"), ("stripe", "Stripe")], max_length=24
                    ),
                ),
                ("event_id", models.CharField(max_length=128)),
                ("signature", models.CharField(blank=True, max_length=256)),
                ("signature_valid", models.BooleanField(default=False)),
                ("raw_body", models.TextField()),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("processing_error", models.TextField(blank=True)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
