# Generated by Django 5.2.14 on 2026-07-08 11:54

import django.db.models.deletion
import django.db.models.fields.json
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        ("pricing", "0001_initial"),
        ("reservations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="reservations.booking",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="concierge_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="reservations.bookingconciergeitem",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="+", to="pricing.currency"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentevent",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_events",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="paymentline",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="against_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refunds_against",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refunds_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refunds",
                to="reservations.booking",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="+", to="pricing.currency"
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="executed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refunds_executed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refunds_rejected",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refunds_requested",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentevent",
            name="refund",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refund_events",
                to="payments.refund",
            ),
        ),
        migrations.AddField(
            model_name="securitydeposit",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="security_deposits",
                to="reservations.booking",
            ),
        ),
        migrations.AddField(
            model_name="securitydeposit",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="securitydeposit",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="+", to="pricing.currency"
            ),
        ),
        migrations.AddField(
            model_name="securitydeposit",
            name="damage_claim",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="security_deposits",
                to="reservations.damageclaim",
            ),
        ),
        migrations.AddField(
            model_name="securitydeposit",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="security_deposits_requested",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="securitydeposit",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="security_deposit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refunds",
                to="payments.securitydeposit",
            ),
        ),
        migrations.AddField(
            model_name="paymentevent",
            name="security_deposit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="security_deposit_events",
                to="payments.securitydeposit",
            ),
        ),
        migrations.AddField(
            model_name="webhookdelivery",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="webhook_deliveries",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="paymentevent",
            name="delivery",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="payments.webhookdelivery",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["booking", "purpose"], name="payments_pa_booking_fb08f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status", "due_at"], name="payments_pa_status_a24582_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["provider_reference"], name="payments_pa_provide_48cfd7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ("pending", "processing", "succeeded")), ("purpose", "deposit")
                ),
                fields=("booking",),
                name="unique_active_deposit_per_booking",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ("pending", "processing", "succeeded")), ("purpose", "balance")
                ),
                fields=("booking",),
                name="unique_active_balance_per_booking",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ("pending", "processing", "succeeded")),
                    ("purpose", "security_deposit"),
                ),
                fields=("booking",),
                name="unique_active_security_deposit_per_booking",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("purpose", "refund"), ("due_at__isnull", False), _negated=True),
                name="payment_refund_has_no_due_at",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("purpose", "concierge"), ("concierge_item__isnull", True), _connector="OR"
                ),
                name="payment_concierge_item_only_for_concierge",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("purpose", "refund"), ("amount__lt", 0), _negated=True),
                name="payment_refund_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)), name="payment_amount_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                models.F("booking"),
                models.F("purpose"),
                django.db.models.fields.json.KeyTextTransform("idempotency_key", "meta"),
                condition=models.Q(("meta__idempotency_key__isnull", False)),
                name="payment_idempotency_key_unique_per_booking_purpose",
            ),
        ),
        migrations.AddIndex(
            model_name="securitydeposit",
            index=models.Index(fields=["booking", "status"], name="payments_se_booking_666b5f_idx"),
        ),
        migrations.AddIndex(
            model_name="securitydeposit",
            index=models.Index(
                fields=["status", "release_scheduled_for"], name="payments_se_status_92bad3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitydeposit",
            index=models.Index(
                fields=["status", "hold_expires_at"], name="payments_se_status_99d02b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="securitydeposit",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="securitydeposit_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="securitydeposit",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "released",
                            "captured",
                            "expired",
                            "failed",
                            "refunded",
                            "partially_refunded",
                        ],
                    ),
                    _negated=True,
                ),
                fields=("booking",),
                name="one_active_security_deposit_per_booking",
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(fields=["booking", "status"], name="payments_re_booking_0e2e74_idx"),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(
                fields=["status", "requested_at"], name="payments_re_status_0cd2b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(fields=["against_payment"], name="payments_re_against_cb8af6_idx"),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="refund_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approved_by__isnull", True),
                    models.Q(("approved_by", models.F("requested_by")), _negated=True),
                    _connector="OR",
                ),
                name="refund_separation_of_duties",
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.UniqueConstraint(
                models.F("booking"),
                django.db.models.fields.json.KeyTextTransform("idempotency_key", "meta"),
                condition=models.Q(("meta__idempotency_key__isnull", False)),
                name="refund_idempotency_key_unique_per_booking",
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["provider", "received_at"], name="payments_we_provide_36ad95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["signature_valid", "processed_at"], name="payments_we_signatu_139132_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="webhookdelivery",
            constraint=models.UniqueConstraint(
                fields=("provider", "event_id"), name="webhookdelivery_unique_provider_event_id"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentevent",
            index=models.Index(
                fields=["payment", "created_at"], name="payments_pa_payment_ec2b3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentevent",
            index=models.Index(
                fields=["refund", "created_at"], name="payments_pa_refund__55468c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentevent",
            index=models.Index(
                fields=["security_deposit", "created_at"], name="payments_pa_securit_a531eb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("payment__isnull", False),
                        ("refund__isnull", True),
                        ("security_deposit__isnull", True),
                    ),
                    models.Q(
                        ("payment__isnull", True),
                        ("refund__isnull", False),
                        ("security_deposit__isnull", True),
                    ),
                    models.Q(
                        ("payment__isnull", True),
                        ("refund__isnull", True),
                        ("security_deposit__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="paymentevent_exactly_one_target",
            ),
        ),
    ]
