# Generated by Django 5.2.14 on 2026-06-01 23:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_payment_legacy_id"),
        ("pricing", "0008_rateplan_fallback_nightly"),
        ("reservations", "0009_booking_booking_cancelled_status_requires_cancelled_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="payment",
            name="unique_active_payment_per_purpose",
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ("pending", "processing", "succeeded")), ("purpose", "deposit")
                ),
                fields=("booking",),
                name="unique_active_deposit_per_booking",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ("pending", "processing", "succeeded")), ("purpose", "balance")
                ),
                fields=("booking",),
                name="unique_active_balance_per_booking",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ("pending", "processing", "succeeded")),
                    ("purpose", "security_deposit"),
                ),
                fields=("booking",),
                name="unique_active_security_deposit_per_booking",
            ),
        ),
    ]
