# Generated by Django 5.2.14 on 2026-06-04 04:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_remove_payment_unique_active_payment_per_purpose_and_more"),
        ("pricing", "0009_remove_ratecard_changeover_weekday"),
        ("reservations", "0016_ownerblockrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("purpose", "refund"), ("due_at__isnull", False), _negated=True),
                name="payment_refund_has_no_due_at",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("purpose", "concierge"), ("concierge_item__isnull", True), _connector="OR"
                ),
                name="payment_concierge_item_only_for_concierge",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("purpose", "refund"), ("amount__lt", 0), _negated=True),
                name="payment_refund_amount_non_negative",
            ),
        ),
    ]
