# Generated by Django 5.2.14 on 2026-06-09 06:54

import django.db.models.functions.comparison
import django.db.models.functions.datetime
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_payment_payment_refund_has_no_due_at_and_more"),
    ]

    operations = [
        # Reference allocator (BUG-007). The column's `db_default` below calls
        # `nextval('payment_reference_seq')`, so the sequence must exist first.
        # `OWNED BY` ties its lifecycle to the column. The name is mirrored in
        # the model's `reference_db_default(... sequence="payment_reference_seq")`
        # (migrations must not import app runtime code, so it's repeated here).
        migrations.RunSQL(
            sql=(
                "CREATE SEQUENCE IF NOT EXISTS payment_reference_seq; "
                "ALTER SEQUENCE payment_reference_seq OWNED BY payments_payment.reference;"
            ),
            reverse_sql="DROP SEQUENCE IF EXISTS payment_reference_seq",
        ),
        migrations.AlterField(
            model_name="payment",
            name="reference",
            field=models.CharField(
                db_default=django.db.models.functions.text.Concat(
                    models.Value("P-"),
                    django.db.models.functions.comparison.Cast(
                        django.db.models.functions.datetime.ExtractYear(
                            django.db.models.functions.datetime.Now()
                        ),
                        output_field=models.CharField(),
                    ),
                    models.Value("-"),
                    django.db.models.functions.comparison.Cast(
                        models.Func(
                            models.Value("payment_reference_seq"),
                            function="nextval",
                            output_field=models.BigIntegerField(),
                        ),
                        output_field=models.CharField(),
                    ),
                    output_field=models.CharField(),
                ),
                max_length=32,
                unique=True,
            ),
        ),
    ]
