# Generated by Django 5.2.14 on 2026-06-09 06:59

import django.db.models.functions.comparison
import django.db.models.functions.datetime
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0005_alter_payment_reference"),
    ]

    operations = [
        # Reference allocators (BUG-007) — each column's `db_default` calls
        # `nextval(...)`, so the sequence must exist first. `OWNED BY` ties its
        # lifecycle to the column. Names mirror the models'
        # `reference_db_default(... sequence=...)` (migrations must not import
        # app runtime code, so they're repeated here).
        migrations.RunSQL(
            sql=(
                "CREATE SEQUENCE IF NOT EXISTS refund_reference_seq; "
                "ALTER SEQUENCE refund_reference_seq OWNED BY payments_refund.reference;"
            ),
            reverse_sql="DROP SEQUENCE IF EXISTS refund_reference_seq",
        ),
        migrations.RunSQL(
            sql=(
                "CREATE SEQUENCE IF NOT EXISTS security_deposit_reference_seq; "
                "ALTER SEQUENCE security_deposit_reference_seq "
                "OWNED BY payments_securitydeposit.reference;"
            ),
            reverse_sql="DROP SEQUENCE IF EXISTS security_deposit_reference_seq",
        ),
        migrations.AlterField(
            model_name="refund",
            name="reference",
            field=models.CharField(
                db_default=django.db.models.functions.text.Concat(
                    models.Value("R-"),
                    django.db.models.functions.comparison.Cast(
                        django.db.models.functions.datetime.ExtractYear(
                            django.db.models.functions.datetime.Now()
                        ),
                        output_field=models.CharField(),
                    ),
                    models.Value("-"),
                    django.db.models.functions.comparison.Cast(
                        models.Func(
                            models.Value("refund_reference_seq"),
                            function="nextval",
                            output_field=models.BigIntegerField(),
                        ),
                        output_field=models.CharField(),
                    ),
                    output_field=models.CharField(),
                ),
                max_length=32,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="securitydeposit",
            name="reference",
            field=models.CharField(
                db_default=django.db.models.functions.text.Concat(
                    models.Value("SD-"),
                    django.db.models.functions.comparison.Cast(
                        django.db.models.functions.datetime.ExtractYear(
                            django.db.models.functions.datetime.Now()
                        ),
                        output_field=models.CharField(),
                    ),
                    models.Value("-"),
                    django.db.models.functions.comparison.Cast(
                        models.Func(
                            models.Value("security_deposit_reference_seq"),
                            function="nextval",
                            output_field=models.BigIntegerField(),
                        ),
                        output_field=models.CharField(),
                    ),
                    output_field=models.CharField(),
                ),
                max_length=32,
                unique=True,
            ),
        ),
    ]
