# Generated by Django 5.2.14 on 2026-06-10 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0006_alter_refund_reference_and_more"),
        ("pricing", "0010_remove_raterule_priority"),
        ("reservations", "0029_booking_booking_one_per_quotation_line"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)), name="payment_amount_non_negative"
            ),
        ),
    ]
