# Generated by Django 5.2.14 on 2026-06-12 05:17

import django.db.models.fields.json
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0007_payment_payment_amount_non_negative"),
        ("pricing", "0010_remove_raterule_priority"),
        ("reservations", "0030_enquiry_flexibility_days"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                models.F("booking"),
                models.F("purpose"),
                django.db.models.fields.json.KeyTextTransform("idempotency_key", "meta"),
                condition=models.Q(("meta__idempotency_key__isnull", False)),
                name="payment_idempotency_key_unique_per_booking_purpose",
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.UniqueConstraint(
                models.F("booking"),
                django.db.models.fields.json.KeyTextTransform("idempotency_key", "meta"),
                condition=models.Q(("meta__idempotency_key__isnull", False)),
                name="refund_idempotency_key_unique_per_booking",
            ),
        ),
    ]
