# Generated by Django 5.2.14 on 2026-06-23 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0008_payment_payment_idempotency_key_unique_per_booking_purpose_and_more"),
        ("reservations", "0037_damageclaim"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="securitydeposit",
            name="damage_claim_id",
        ),
        migrations.AddField(
            model_name="securitydeposit",
            name="damage_claim",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="security_deposits",
                to="reservations.damageclaim",
            ),
        ),
    ]
