"""PropertyContactAssignment, Guest, Enquiry loaders.

PropertyContactAssignment: legacy VillaContactMapping joins Property+Contact;
VillaContactRoleMapping carries the role(s). Each (mapping, role) combination
becomes one assignment row.

Guest: VillaClientDetails -> Guest. Country FK resolved via legacy_id.

Enquiry: VillaEnquire -> Enquiry. Most operational; status enum is
remapped from the legacy int. Reference is auto-generated by Enquiry.save.
"""

from __future__ import annotations

from typing import Any

from accounts.enums import ContactRole
from accounts.models import Contact
from data_migration.base import BaseLoader, LoadReport
from properties.models.contacts import PropertyContactAssignment
from properties.models.geo import Country, Region
from properties.models.property import Property
from reservations.enums import EnquirySource, EnquiryStatus
from reservations.models.enquiry import Enquiry
from reservations.models.guest import Guest

_ROLE_MAP = {
    1: ContactRole.OWNER,
    2: ContactRole.AGENT,
    3: ContactRole.MANAGER,
    4: ContactRole.MANAGER,
    5: ContactRole.OWNERS_REPRESENTATIVE,
}


class PropertyContactAssignmentLoader(BaseLoader):
    """One row per (VillaContactMapping, VillaContactRoleMapping.role) pair.

    Composite legacy_id = "<mappingId>-<roleId>" to keep them distinct.
    """

    name = "property_contact_assignment"
    target_model = PropertyContactAssignment
    legacy_query = (
        "SELECT m.Id AS MappingId, m.PropertyId, m.ContactId, m.IsPrimaryContact, "
        "r.RoleId, COALESCE(r.Id, m.Id * -1) AS RoleMappingId "
        "FROM VillaContactMapping m "
        "LEFT JOIN VillaContactRoleMapping r ON r.VillaContactMappingId = m.Id"
    )

    def _process_row(self, row: dict[str, Any], report: LoadReport) -> None:
        prop = Property.objects.filter(legacy_id=str(row.get("PropertyId") or "")).first()
        contact = Contact.objects.filter(legacy_id=str(row.get("ContactId") or "")).first()
        if prop is None or contact is None:
            report.skipped += 1
            return
        role = _ROLE_MAP.get(row.get("RoleId") or 0, ContactRole.OWNER)
        composite = f"{row['MappingId']}-{row.get('RoleId') or 0}"
        is_primary = bool(row.get("IsPrimaryContact"))
        # One primary per (property, role).
        if (
            is_primary
            and PropertyContactAssignment.objects.filter(
                property=prop,
                role=role,
                is_primary=True,
                end_date__isnull=True,
            )
            .exclude(legacy_id=composite)
            .exists()
        ):
            is_primary = False
        _, created = PropertyContactAssignment.objects.update_or_create(
            legacy_id=composite,
            defaults={
                "property": prop,
                "contact": contact,
                "role": role,
                "is_primary": is_primary,
            },
        )
        if created:
            report.created += 1
        else:
            report.updated += 1


class GuestLoader(BaseLoader):
    name = "guest"
    target_model = Guest
    legacy_query = (
        "SELECT Id, Title, FirstName, LastName, MobileNo, Email, "
        "Notes, CountryId, Town, Postcode, AddressLine1, AddressLine2 "
        "FROM VillaClientDetails"
    )

    def transform(self, row: dict[str, Any]) -> dict[str, Any] | None:
        first = (row.get("FirstName") or "").strip()[:128]
        last = (row.get("LastName") or "").strip()[:128]
        email = (row.get("Email") or "").strip().lower()
        if not (first or last) or not email or "@" not in email:
            return None
        country = (
            Country.objects.filter(legacy_id=str(row["CountryId"])).first()
            if row.get("CountryId")
            else None
        )
        return {
            "title": (row.get("Title") or "").strip()[:16],
            "first_name": first or "(unknown)",
            "last_name": last or "(unknown)",
            "email": email[:254],
            "phone": (row.get("MobileNo") or "").strip()[:32],
            "address_line_1": (row.get("AddressLine1") or "").strip()[:255],
            "address_line_2": (row.get("AddressLine2") or "").strip()[:255],
            "town": (row.get("Town") or "").strip()[:128],
            "post_code": (row.get("Postcode") or "").strip()[:32],
            "country": country,
            "notes": (row.get("Notes") or "").strip(),
        }


_ENQUIRY_STATUS_MAP = {
    1: EnquiryStatus.NEW,
    2: EnquiryStatus.CONTACTED,
    3: EnquiryStatus.QUOTED,
    4: EnquiryStatus.CONVERTED,
    5: EnquiryStatus.LOST,
}


class EnquiryLoader(BaseLoader):
    """VillaEnquire -> Enquiry.

    Inbound lead with optional Property/Region FKs. Status int → enum. The
    reference is auto-generated by Enquiry.save(). Some legacy VillaId values
    are CSVs (e.g. "1,2,3") — we only resolve when a single id parses.
    """

    name = "enquiry"
    target_model = Enquiry
    legacy_query = (
        "SELECT Id, FirstName, LastName, Email, CountryCode, MobileNo, "
        "VillaId, RegionsId, FromDate, ToDate, MinBed, MaxBed, "
        "Adult, Children, Notes, Status, AgentId, EnquiryNo, ReferralCode, "
        "RequestType, CreatedBy "
        "FROM VillaEnquire"
    )

    def transform(self, row: dict[str, Any]) -> dict[str, Any] | None:
        first = (row.get("FirstName") or "").strip()[:128]
        last = (row.get("LastName") or "").strip()[:128]
        if not (first or last):
            first = first or "(anon)"

        # VillaId is nvarchar in legacy — sometimes a single int, sometimes CSV.
        prop = None
        villa_raw = (row.get("VillaId") or "").strip()
        if villa_raw and "," not in villa_raw and villa_raw.isdigit():
            prop = Property.objects.filter(legacy_id=villa_raw).first()
        region = None
        region_raw = (row.get("RegionsId") or "").strip()
        if region_raw and "," not in region_raw and region_raw.isdigit():
            region = Region.objects.filter(legacy_id=region_raw).first()

        agent = (
            Contact.objects.filter(legacy_id=str(row["AgentId"])).first()
            if row.get("AgentId")
            else None
        )

        date_from: Any = row.get("FromDate")
        date_to: Any = row.get("ToDate")
        if date_from is not None and hasattr(date_from, "date"):
            date_from = date_from.date()
        if date_to is not None and hasattr(date_to, "date"):
            date_to = date_to.date()

        cc = (row.get("CountryCode") or "").strip()
        phone = (row.get("MobileNo") or "").strip()
        if cc and phone:
            phone = f"+{cc.lstrip('+')} {phone}"
        phone = phone[:32]

        email = (row.get("Email") or "").strip().lower()
        if "@" not in email:
            email = ""

        return {
            "reference": (row.get("EnquiryNo") or f"E-{row['Id']:06d}")[:32],
            "first_name": first,
            "last_name": last,
            "email": email,
            "phone": phone,
            "property": prop,
            "region": region,
            "agent": agent,
            "date_from": date_from,
            "date_to": date_to,
            "adults": int(row.get("Adult") or 2),
            "children": int(row.get("Children") or 0),
            "min_bedrooms": (int(row["MinBed"]) if row.get("MinBed") else None),
            "referral_code": (row.get("ReferralCode") or "").strip()[:64],
            "site_source": EnquirySource.MAIN_WEBSITE,
            "status": _ENQUIRY_STATUS_MAP.get(row.get("Status") or 0, EnquiryStatus.NEW),
            "inbound_message": (row.get("Notes") or "").strip(),
        }
