"""PropertyContactAssignment, Client (Person), Enquiry loaders.

PropertyContactAssignment: legacy VillaContactMapping joins Property+Person;
VillaContactRoleMapping carries the role(s). Each (mapping, role) combination
becomes one assignment row.

Client: VillaClientDetails -> accounts.Person (GAP-045 D5-3 — the legacy import
writes Person DIRECTLY, no Guest). Keyed `legacy_id="client-{Id}"`,
`kind=CUSTOMER`; Country FK resolved via legacy_id; the PRIMARY email/phone are
reconciled IN PLACE so a re-run never duplicates a primary child.

Enquiry: VillaEnquire -> Enquiry. Most operational; status enum is
remapped from the legacy int. Reference is auto-generated by Enquiry.save.
"""

from __future__ import annotations

from typing import Any

from accounts.enums import ContactRole, PersonKind, PersonStatus
from accounts.models import Person
from data_migration.base import BaseLoader, LoadReport
from data_migration.loaders.sentinels import CLIENT_LEGACY_PREFIX
from properties.models.contacts import PropertyContactAssignment
from properties.models.geo import Country, Region
from properties.models.property import Property
from reservations.enums import EnquirySource, EnquiryStatus
from reservations.models.enquiry import Enquiry
from reservations.phone import to_e164
from reservations.services.person_sync import (
    reconcile_primary_email,
    reconcile_primary_phone,
)

_ROLE_MAP = {
    1: ContactRole.OWNER,
    2: ContactRole.AGENT,
    3: ContactRole.MANAGER,
    4: ContactRole.MANAGER,
    5: ContactRole.OWNERS_REPRESENTATIVE,
}


class PropertyContactAssignmentLoader(BaseLoader):
    """One row per (VillaContactMapping, VillaContactRoleMapping.role) pair.

    Composite legacy_id = "<mappingId>-<roleId>" to keep them distinct.
    """

    name = "property_contact_assignment"
    target_model = PropertyContactAssignment
    legacy_query = (
        "SELECT m.Id AS MappingId, m.PropertyId, m.ContactId, m.IsPrimaryContact, "
        "r.RoleId, COALESCE(r.Id, m.Id * -1) AS RoleMappingId "
        "FROM VillaContactMapping m "
        "LEFT JOIN VillaContactRoleMapping r ON r.VillaContactMappingId = m.Id"
    )

    def _process_row(self, row: dict[str, Any], report: LoadReport) -> None:
        prop = Property.objects.filter(legacy_id=str(row.get("PropertyId") or "")).first()
        contact = Person.objects.filter(legacy_id=str(row.get("ContactId") or "")).first()
        if prop is None or contact is None:
            report.skipped += 1
            return
        role = _ROLE_MAP.get(row.get("RoleId") or 0, ContactRole.OWNER)
        composite = f"{row['MappingId']}-{row.get('RoleId') or 0}"
        is_primary = bool(row.get("IsPrimaryContact"))
        # One primary per (property, role).
        if (
            is_primary
            and PropertyContactAssignment.objects.filter(
                property=prop,
                role=role,
                is_primary=True,
                end_date__isnull=True,
            )
            .exclude(legacy_id=composite)
            .exists()
        ):
            is_primary = False
        _, created = PropertyContactAssignment.objects.update_or_create(
            legacy_id=composite,
            defaults={
                "property": prop,
                "contact": contact,
                "role": role,
                "is_primary": is_primary,
            },
        )
        if created:
            report.created += 1
        else:
            report.updated += 1


class ClientLoader(BaseLoader):
    """VillaClientDetails -> accounts.Person (GAP-045 D5-3).

    The legacy import now writes a unified `Person` directly — no `Guest`. Each
    client becomes a `kind=CUSTOMER` Person keyed `legacy_id="client-{Id}"`, with
    its single legacy email/phone reconciled into a PRIMARY `PersonEmail` /
    `PersonPhone` child IN PLACE (via the shared `reconcile_primary_*` helpers, so
    a re-run — or a changed legacy email — never blind-creates a second PRIMARY
    row and trips `one_primary_*_per_contact`).

    `transform` stays a pure dict-transform (legacy row → Person defaults plus the
    transient `_email`/`_phone`); `_process_row` does the multi-row write
    (Person + the two reconciled children), so the children can't be expressed by
    the BaseLoader single-upsert path.
    """

    name = "client"
    target_model = Person
    legacy_query = (
        "SELECT Id, Title, FirstName, LastName, MobileNo, Email, "
        "Notes, CountryId, Town, Postcode, AddressLine1, AddressLine2 "
        "FROM VillaClientDetails"
    )

    def transform(self, row: dict[str, Any]) -> dict[str, Any] | None:
        first = (row.get("FirstName") or "").strip()[:128]
        last = (row.get("LastName") or "").strip()[:128]
        if not (first or last):
            # No identity at all — nothing worth importing (the documented
            # no-name gap; reconcile_legacy carries expected_gap=1 for it).
            return None
        # Email is optional; absence is None, never a synthetic. A phone-only
        # client is first-class valid (no longer dropped).
        email_raw = (row.get("Email") or "").strip().lower()
        email = email_raw[:254] if "@" in email_raw else None
        phone = to_e164((row.get("MobileNo") or "").strip())[:32]
        # A contactless legacy row maps to INACTIVE (the Guest path's ARCHIVED;
        # the SYNCED status map is ARCHIVED→INACTIVE / ANONYMIZED→ANONYMIZED) —
        # the honest exemption rather than failing the import. No legacy
        # VillaClientDetails column carries an ANONYMIZED disposition, so only
        # ACTIVE / INACTIVE arise from the import itself.
        status = PersonStatus.ACTIVE if (email or phone) else PersonStatus.INACTIVE
        country = (
            Country.objects.filter(legacy_id=str(row["CountryId"])).first()
            if row.get("CountryId")
            else None
        )
        return {
            "title": (row.get("Title") or "").strip()[:16],
            "first_name": first or "(unknown)",
            "last_name": last or "(unknown)",
            "status": status.value,
            "kind": PersonKind.CUSTOMER.value,
            "address_line_1": (row.get("AddressLine1") or "").strip()[:255],
            "address_line_2": (row.get("AddressLine2") or "").strip()[:255],
            "town": (row.get("Town") or "").strip()[:128],
            "post_code": (row.get("Postcode") or "").strip()[:32],
            "country": country,
            "notes": (row.get("Notes") or "").strip(),
            # Transient channel values — popped in _process_row, not Person
            # columns (Person holds email/phone as PersonEmail/PersonPhone rows).
            "_email": email,
            "_phone": phone,
        }

    def _process_row(self, row: dict[str, Any], report: LoadReport) -> None:
        legacy_id = row.get(self.legacy_pk_column)
        if legacy_id is None:
            report.skipped += 1
            return
        kwargs = self.transform(row)
        if kwargs is None:
            report.skipped += 1
            return
        email = kwargs.pop("_email")
        phone = kwargs.pop("_phone")
        person, created = Person.objects.update_or_create(
            legacy_id=f"{CLIENT_LEGACY_PREFIX}{legacy_id}",
            defaults=kwargs,
        )
        # In-place reconcile of the single legacy channel onto the PRIMARY child
        # (shared with sync_person_from_guest) — never a blind create on re-run.
        reconcile_primary_email(person, email)
        reconcile_primary_phone(person, phone or "")
        if created:
            report.created += 1
        else:
            report.updated += 1


_ENQUIRY_STATUS_MAP = {
    1: EnquiryStatus.NEW,
    2: EnquiryStatus.CONTACTED,
    3: EnquiryStatus.QUOTED,
    4: EnquiryStatus.CONVERTED,
    5: EnquiryStatus.LOST,
}


class EnquiryLoader(BaseLoader):
    """VillaEnquire -> Enquiry.

    Inbound lead with optional Property/Region FKs. Status int → enum. We set
    `reference` explicitly from the legacy `EnquiryNo` (falling back to
    `E-{Id:06d}`); that explicit value wins over the column's `db_default`
    sequence, which only allocates for organically-created enquiries. Some
    legacy VillaId values are CSVs (e.g. "1,2,3") — we only resolve when a
    single id parses.
    """

    name = "enquiry"
    target_model = Enquiry
    legacy_query = (
        "SELECT Id, FirstName, LastName, Email, CountryCode, MobileNo, "
        "VillaId, RegionsId, FromDate, ToDate, MinBed, MaxBed, "
        "Adult, Children, Notes, Status, AgentId, EnquiryNo, ReferralCode, "
        "RequestType, CreatedBy "
        "FROM VillaEnquire"
    )

    def transform(self, row: dict[str, Any]) -> dict[str, Any] | None:
        first = (row.get("FirstName") or "").strip()[:128]
        last = (row.get("LastName") or "").strip()[:128]
        if not (first or last):
            first = first or "(anon)"

        # VillaId is nvarchar in legacy — sometimes a single int, sometimes CSV.
        prop = None
        villa_raw = (row.get("VillaId") or "").strip()
        if villa_raw and "," not in villa_raw and villa_raw.isdigit():
            prop = Property.objects.filter(legacy_id=villa_raw).first()
        region = None
        region_raw = (row.get("RegionsId") or "").strip()
        if region_raw and "," not in region_raw and region_raw.isdigit():
            region = Region.objects.filter(legacy_id=region_raw).first()

        agent = (
            Person.objects.filter(legacy_id=str(row["AgentId"])).first()
            if row.get("AgentId")
            else None
        )

        date_from: Any = row.get("FromDate")
        date_to: Any = row.get("ToDate")
        if date_from is not None and hasattr(date_from, "date"):
            date_from = date_from.date()
        if date_to is not None and hasattr(date_to, "date"):
            date_to = date_to.date()

        # Normalize to E.164 using the legacy numeric calling code as the
        # region anchor (replaces the crude `+{cc} {number}` concatenation).
        cc = (row.get("CountryCode") or "").strip()
        phone = to_e164((row.get("MobileNo") or "").strip(), country_code=cc or None)[:32]

        email = (row.get("Email") or "").strip().lower()
        if "@" not in email:
            email = ""

        return {
            "reference": (row.get("EnquiryNo") or f"E-{row['Id']:06d}")[:32],
            "first_name": first,
            "last_name": last,
            "email": email,
            "phone": phone,
            "property": prop,
            "region": region,
            "agent": agent,
            "date_from": date_from,
            "date_to": date_to,
            "adults": int(row.get("Adult") or 2),
            "children": int(row.get("Children") or 0),
            "min_bedrooms": (int(row["MinBed"]) if row.get("MinBed") else None),
            "referral_code": (row.get("ReferralCode") or "").strip()[:64],
            "site_source": EnquirySource.MAIN_WEBSITE,
            "status": _ENQUIRY_STATUS_MAP.get(row.get("Status") or 0, EnquiryStatus.NEW),
            "inbound_message": (row.get("Notes") or "").strip(),
        }
