# Generated by Django 5.2.14 on 2026-07-08 11:54

import core.fields
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.datetime
import django.db.models.functions.text
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        # Hand-added: the enquiry/damage-claim reference columns below carry a
        # `DEFAULT nextval(...)`, so the sequences must already exist.
        ("core", "0003_reference_sequences"),
        ("pricing", "0001_initial"),
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestPreferenceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=32, unique=True)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("adults", models.PositiveSmallIntegerField()),
                ("children", models.PositiveSmallIntegerField(default=0)),
                ("pricing_snapshot", models.JSONField(default=dict)),
                (
                    "rental_price",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                (
                    "adjustment",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                (
                    "balance_due",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                ("balance_due_at", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_owner_approval", "Pending owner approval"),
                            ("awaiting_deposit", "Awaiting deposit"),
                            ("deposit_paid", "Deposit paid"),
                            ("awaiting_balance", "Awaiting balance"),
                            ("balance_paid", "Balance paid"),
                            ("checked_in", "Checked in"),
                            ("checked_out", "Checked out"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("declined", "Declined"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "site_source",
                    models.CharField(
                        choices=[
                            ("main_website", "Main website"),
                            ("agent_portal", "Agent portal"),
                            ("email_inbound", "Inbound email"),
                            ("phone", "Phone"),
                            ("other", "Other"),
                        ],
                        default="main_website",
                        max_length=16,
                    ),
                ),
                ("terms_accepted_at", models.DateTimeField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("card", "Card"), ("bank_transfer", "Bank transfer")],
                        default="card",
                        max_length=16,
                    ),
                ),
                ("cancel_reason", models.TextField(blank=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings_as_agent",
                        to="accounts.person",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="pricing.currency",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings_as_customer",
                        to="accounts.person",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="properties.property",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingConciergeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tier",
                    models.CharField(
                        choices=[("quintessential", "Quintessential"), ("signature", "Signature")],
                        default="quintessential",
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("day", "Day"),
                            ("stay", "Stay"),
                            ("event", "Event"),
                            ("hour", "Hour"),
                        ],
                        default="stay",
                        max_length=8,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("delivered", "Delivered"),
                        ],
                        default="requested",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concierge_items",
                        to="reservations.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="pricing.currency",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="BookingHold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("quotation_open", "Quotation open"),
                            ("owner_block", "Owner block"),
                            ("maintenance", "Maintenance"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holds",
                        to="reservations.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holds",
                        to="properties.property",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DamageClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        db_default=django.db.models.functions.text.Concat(
                            models.Value("DC-"),
                            django.db.models.functions.comparison.Cast(
                                django.db.models.functions.datetime.ExtractYear(
                                    django.db.models.functions.datetime.Now()
                                ),
                                output_field=models.CharField(),
                            ),
                            models.Value("-"),
                            django.db.models.functions.comparison.Cast(
                                models.Func(
                                    models.Value("damage_claim_reference_seq"),
                                    function="nextval",
                                    output_field=models.BigIntegerField(),
                                ),
                                output_field=models.CharField(),
                            ),
                            output_field=models.CharField(),
                        ),
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("approved", "Approved"),
                            ("settled", "Settled"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("itemized_lines", models.JSONField(blank=True, default=list)),
                ("accepted_by_guest_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="damage_claims",
                        to="reservations.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="pricing.currency",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DamageClaimPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="damage_claims/%Y/%m/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "damage_claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="reservations.damageclaim",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["damage_claim_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        db_default=django.db.models.functions.text.Concat(
                            models.Value("E-"),
                            django.db.models.functions.comparison.Cast(
                                django.db.models.functions.datetime.ExtractYear(
                                    django.db.models.functions.datetime.Now()
                                ),
                                output_field=models.CharField(),
                            ),
                            models.Value("-"),
                            django.db.models.functions.comparison.Cast(
                                models.Func(
                                    models.Value("enquiry_reference_seq"),
                                    function="nextval",
                                    output_field=models.BigIntegerField(),
                                ),
                                output_field=models.CharField(),
                            ),
                            output_field=models.CharField(),
                        ),
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=128)),
                ("last_name", models.CharField(blank=True, max_length=128)),
                ("email", core.fields.CIEmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                (
                    "contact_method",
                    models.CharField(
                        blank=True,
                        choices=[("email", "Email"), ("phone", "Phone"), ("sms", "SMS")],
                        max_length=8,
                        null=True,
                    ),
                ),
                ("date_from", models.DateField(blank=True, null=True)),
                ("date_to", models.DateField(blank=True, null=True)),
                ("is_flexible", models.BooleanField(default=False)),
                (
                    "flexibility_days",
                    models.PositiveSmallIntegerField(
                        default=0, validators=[django.core.validators.MaxValueValidator(3)]
                    ),
                ),
                ("adults", models.PositiveSmallIntegerField(default=2)),
                ("children", models.PositiveSmallIntegerField(default=0)),
                ("min_bedrooms", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("availability", "Availability"),
                            ("info", "Info"),
                            ("quote", "Quote"),
                            ("brochure", "Brochure"),
                            ("other", "Other"),
                        ],
                        default="quote",
                        max_length=16,
                    ),
                ),
                ("referral_code", models.CharField(blank=True, max_length=64)),
                (
                    "site_source",
                    models.CharField(
                        choices=[
                            ("main_website", "Main website"),
                            ("agent_portal", "Agent portal"),
                            ("email_inbound", "Inbound email"),
                            ("phone", "Phone"),
                            ("other", "Other"),
                        ],
                        default="main_website",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("progressing", "Progressing"),
                            ("quote_sent", "Quote sent"),
                            ("follow_up", "Follow-up"),
                            ("dead", "Dead"),
                            ("converted", "Converted"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                (
                    "lost_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("found_alternative", "Found alternative"),
                            ("availability", "Availability"),
                            ("different_destination", "Different destination"),
                            ("no_group_consensus", "No group consensus"),
                            ("unknown", "Unknown"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "lead_status",
                    models.CharField(
                        choices=[
                            ("hot", "Hot"),
                            ("warm", "Warm"),
                            ("cold", "Cold"),
                            ("dead", "Dead"),
                        ],
                        default="warm",
                        max_length=8,
                    ),
                ),
                ("inbound_message", models.TextField(blank=True)),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enquiries_as_agent",
                        to="accounts.person",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_enquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enquiries_as_customer",
                        to="accounts.person",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enquiries",
                        to="properties.property",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enquiries",
                        to="properties.region",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "enquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnquiryEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("progressing", "Progressing"),
                            ("quote_sent", "Quote sent"),
                            ("follow_up", "Follow-up"),
                            ("dead", "Dead"),
                            ("converted", "Converted"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("progressing", "Progressing"),
                            ("quote_sent", "Quote sent"),
                            ("follow_up", "Follow-up"),
                            ("dead", "Dead"),
                            ("converted", "Converted"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("status_change", "Status change"),
                            ("assigned", "Assigned"),
                            ("unassigned", "Unassigned"),
                            ("contacted", "Contacted"),
                            ("quote_sent", "Quote sent"),
                            ("follow_up", "Follow-up"),
                            ("converted", "Converted"),
                            ("lost", "Lost"),
                            ("reopened", "Reopened"),
                            ("note_added", "Note added"),
                            ("lead_status_changed", "Lead status changed"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("owner", "Owner"),
                            ("webhook", "Webhook"),
                            ("system", "System"),
                            ("admin", "Admin"),
                        ],
                        default="user",
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="reservations.enquiry",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnquiryNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("internal", "Internal"),
                            ("preferences", "Preferences"),
                        ],
                        default="general",
                        max_length=16,
                    ),
                ),
                ("body", models.TextField()),
                ("is_pinned", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_collection",
                        to="reservations.enquiry",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="OwnerBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("ical", "iCal feed")],
                        default="manual",
                        max_length=16,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("owner_stay", "Owner stay"),
                            ("maintenance", "Maintenance"),
                            ("other", "Other"),
                        ],
                        default="owner_stay",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("approved", "Approved"), ("cancelled", "Cancelled")],
                        default="approved",
                        max_length=16,
                    ),
                ),
                ("contested_at", models.DateTimeField(blank=True, null=True)),
                ("contest_reason", models.TextField(blank=True, default="")),
                (
                    "contested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_block_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_block_requests",
                        to="properties.property",
                    ),
                ),
                (
                    "resulting_hold",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="reservations.bookinghold",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OwnerBlockUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("created", "Created"), ("cancelled", "Cancelled")], max_length=16
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updates",
                        to="reservations.ownerblock",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OwnerBlockUpdateSeen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "update",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seen_marks",
                        to="reservations.ownerblockupdate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=32, unique=True)),
                ("number", models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ("is_unbranded", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("cancel_reason", models.TextField(blank=True)),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotations_as_agent",
                        to="accounts.person",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotations",
                        to="reservations.enquiry",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotations_as_customer",
                        to="accounts.person",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GuestPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_preferences",
                        to="accounts.person",
                    ),
                ),
                (
                    "preference_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reservations.guestpreferencetype",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guest_preferences",
                        to="reservations.quotation",
                    ),
                ),
            ],
            options={
                "ordering": ["person_id", "preference_type_id"],
            },
        ),
        migrations.AddField(
            model_name="bookinghold",
            name="quotation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holds",
                to="reservations.quotation",
            ),
        ),
        migrations.CreateModel(
            name="QuotationLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("adults", models.PositiveSmallIntegerField()),
                ("children", models.PositiveSmallIntegerField(default=0)),
                ("pricing_snapshot", models.JSONField(default=dict)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("inclusions", models.TextField(blank=True)),
                ("price_override_reason", models.TextField(blank=True)),
                ("is_selected", models.BooleanField(default=False)),
                ("is_manual", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="pricing.currency",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotation_lines",
                        to="properties.property",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="reservations.quotation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.AddField(
            model_name="bookinghold",
            name="quotation_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="holds",
                to="reservations.quotationline",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="quotation_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="reservations.quotationline",
            ),
        ),
        migrations.CreateModel(
            name="TermsVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.CharField(max_length=32, unique=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("body_markdown", models.TextField()),
                ("is_current", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("is_current",),
                        name="only_one_current_terms_version",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="quotation",
            name="terms_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="reservations.termsversion",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="terms_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="reservations.termsversion",
            ),
        ),
        migrations.CreateModel(
            name="BookingChargeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("notes", models.TextField(blank=True)),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charge_items",
                        to="reservations.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="pricing.currency",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount", 0), _negated=True),
                        name="bookingchargeitem_amount_nonzero",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BookingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_owner_approval", "Pending owner approval"),
                            ("awaiting_deposit", "Awaiting deposit"),
                            ("deposit_paid", "Deposit paid"),
                            ("awaiting_balance", "Awaiting balance"),
                            ("balance_paid", "Balance paid"),
                            ("checked_in", "Checked in"),
                            ("checked_out", "Checked out"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("declined", "Declined"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_owner_approval", "Pending owner approval"),
                            ("awaiting_deposit", "Awaiting deposit"),
                            ("deposit_paid", "Deposit paid"),
                            ("awaiting_balance", "Awaiting balance"),
                            ("balance_paid", "Balance paid"),
                            ("checked_in", "Checked in"),
                            ("checked_out", "Checked out"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("declined", "Declined"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("owner", "Owner"),
                            ("webhook", "Webhook"),
                            ("system", "System"),
                            ("admin", "Admin"),
                        ],
                        default="user",
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="reservations.booking",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["booking", "created_at"], name="reservation_booking_fceca5_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BookingGuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("co_traveller", "Co-traveller"),
                            ("payer", "Payer"),
                            ("cc_only", "CC only"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "email_override",
                    core.fields.CIEmailField(blank=True, default="", max_length=254),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_guests",
                        to="reservations.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_guests",
                        to="accounts.person",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["booking_id", "role", "id"],
                "indexes": [
                    models.Index(fields=["booking", "role"], name="reservation_booking_d40f51_idx"),
                    models.Index(fields=["person", "role"], name="reservation_person__8b28ce_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("booking", "person", "role"),
                        name="bookingguest_unique_booking_person_role",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("role", "lead")),
                        fields=("booking",),
                        name="bookingguest_one_lead_per_booking",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("role", "payer")),
                        fields=("booking",),
                        name="bookingguest_one_payer_per_booking",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BookingNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("internal", "Internal"),
                            ("concierge", "Concierge"),
                            ("villa", "Villa"),
                        ],
                        default="general",
                        max_length=16,
                    ),
                ),
                ("body", models.TextField()),
                ("is_pinned", models.BooleanField(default=False)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("staff_only", "Staff only"),
                            ("owner", "Owner"),
                            ("guest", "Guest"),
                        ],
                        default="staff_only",
                        max_length=16,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_collection",
                        to="reservations.booking",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["booking", "created_at"], name="reservation_booking_5c51e0_idx"
                    ),
                    models.Index(fields=["booking", "kind"], name="reservation_booking_d75b10_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BookingServiceCoverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("car", "Car hire"),
                            ("transfers", "Transfers"),
                            ("boat", "Boat"),
                            ("chef", "Chef"),
                            ("grocery", "Grocery"),
                            ("firstnight", "First night"),
                            ("restaurant", "Restaurant"),
                            ("gifting", "Gifting"),
                            ("activities", "Activities"),
                            ("spa", "Spa"),
                            ("wine", "Wine"),
                            ("nanny", "Nanny"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("working_on_it", "Working on it"),
                            ("waiting", "Waiting"),
                            ("arranged_independently", "Arranged independently"),
                            ("not_required", "Not required"),
                            ("done", "Done"),
                        ],
                        default="not_started",
                        max_length=24,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_coverage",
                        to="reservations.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["service"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("booking", "service"), name="uniq_booking_service_coverage"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="damageclaim",
            index=models.Index(fields=["booking", "status"], name="reservation_booking_9180c6_idx"),
        ),
        migrations.AddConstraint(
            model_name="damageclaim",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="damage_claim_amount_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="enquiry",
            index=models.Index(
                fields=["status", "created_at"], name="reservation_status_260787_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enquiry",
            index=models.Index(fields=["email"], name="reservation_email_e6eb6a_idx"),
        ),
        migrations.AddIndex(
            model_name="enquiry",
            index=models.Index(
                fields=["property", "date_from"], name="reservation_propert_ccfa00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enquiry",
            index=models.Index(
                fields=["lead_status", "status"], name="reservation_lead_st_c08021_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="enquiry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "dead"), _negated=True),
                    models.Q(("lost_reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="enquiry_dead_requires_lost_reason",
            ),
        ),
        migrations.AddIndex(
            model_name="enquiryevent",
            index=models.Index(
                fields=["enquiry", "created_at"], name="reservation_enquiry_72ea51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enquirynote",
            index=models.Index(
                fields=["enquiry", "created_at"], name="reservation_enquiry_a6dd57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ownerblock",
            index=models.Index(
                fields=["property", "status"], name="reservation_propert_17c4d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ownerblock",
            index=models.Index(
                fields=["created_by", "status"], name="reservation_created_88b6bd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ownerblock",
            constraint=models.CheckConstraint(
                condition=models.Q(("date_from__lt", models.F("date_to"))),
                name="ownerblockrequest_date_from_lt_date_to",
            ),
        ),
        migrations.AddConstraint(
            model_name="ownerblock",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source", "ical"), ("created_by__isnull", False), _connector="OR"
                ),
                name="ownerblock_manual_requires_creator",
            ),
        ),
        migrations.AddConstraint(
            model_name="ownerblock",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status", "approved"), models.Q(("idempotency_key", ""), _negated=True)
                ),
                fields=("property", "idempotency_key"),
                name="unique_active_ical_block_per_property_key",
            ),
        ),
        migrations.AddIndex(
            model_name="ownerblockupdate",
            index=models.Index(
                fields=["block", "created_at"], name="reservation_block_i_d41050_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ownerblockupdateseen",
            constraint=models.UniqueConstraint(
                fields=("update", "user"), name="ownerblockupdateseen_unique_update_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="guestpreference",
            constraint=models.UniqueConstraint(
                fields=("person", "preference_type", "quotation"), name="unique_person_preference"
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationline",
            constraint=models.CheckConstraint(
                condition=models.Q(("date_from__lt", models.F("date_to"))),
                name="quotationline_date_from_lt_date_to",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_selected", True)),
                fields=("quotation",),
                name="one_selected_line_per_quotation",
            ),
        ),
        migrations.AddIndex(
            model_name="bookinghold",
            index=models.Index(
                fields=["property", "released_at", "expires_at"],
                name="reservation_propert_cb20a5_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookinghold",
            constraint=models.CheckConstraint(
                condition=models.Q(("date_from__lt", models.F("date_to"))),
                name="bookinghold_date_from_lt_date_to",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookinghold",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quotation__isnull", False),
                    ("booking__isnull", False),
                    ("reason__in", ["owner_block", "maintenance", "manual"]),
                    _connector="OR",
                ),
                name="bookinghold_has_source_or_blocking_reason",
            ),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(
                fields=["status", "expires_at"], name="reservation_status_ec9485_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["property", "status", "date_from"], name="reservation_propert_ab58fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["status", "balance_due_at"], name="reservation_status_466633_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["reference"], name="reservation_referen_661cad_idx"),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("date_from__lt", models.F("date_to"))),
                name="booking_date_from_lt_date_to",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cancelled_at__isnull", True), ("status", "cancelled"), _connector="OR"
                ),
                name="booking_cancelled_at_implies_cancelled_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cancelled_at__isnull", False),
                    models.Q(("status", "cancelled"), _negated=True),
                    _connector="OR",
                ),
                name="booking_cancelled_status_requires_cancelled_at",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("archived_at__isnull", True),
                    ("status__in", ("checked_out", "cancelled", "expired", "declined")),
                    _connector="OR",
                ),
                name="booking_archived_at_requires_terminal_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                fields=("quotation_line",), name="booking_one_per_quotation_line"
            ),
        ),
    ]
