# Generated by Django 5.2.14 on 2026-05-12 22:07

import core.fields
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_contact_contactemail_contactphone_usersession_and_more"),
        ("pricing", "0003_raterule_exclude_constraint"),
        ("properties", "0002_groupfinance_propertyfinance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=32, unique=True)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("adults", models.PositiveSmallIntegerField()),
                ("children", models.PositiveSmallIntegerField(default=0)),
                ("pricing_snapshot", models.JSONField(default=dict)),
                (
                    "rental_price",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                (
                    "adjustment",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                (
                    "balance_due",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                ("balance_due_at", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_owner_approval", "Pending owner approval"),
                            ("awaiting_deposit", "Awaiting deposit"),
                            ("deposit_paid", "Deposit paid"),
                            ("awaiting_balance", "Awaiting balance"),
                            ("balance_paid", "Balance paid"),
                            ("checked_in", "Checked in"),
                            ("checked_out", "Checked out"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("declined", "Declined"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "site_source",
                    models.CharField(
                        choices=[
                            ("main_website", "Main website"),
                            ("agent_portal", "Agent portal"),
                            ("email_inbound", "Inbound email"),
                            ("phone", "Phone"),
                            ("other", "Other"),
                        ],
                        default="main_website",
                        max_length=16,
                    ),
                ),
                ("terms_accepted_at", models.DateTimeField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("card", "Card"), ("bank_transfer", "Bank transfer")],
                        default="card",
                        max_length=16,
                    ),
                ),
                ("cancel_reason", models.TextField(blank=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings_as_agent",
                        to="accounts.contact",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="pricing.currency",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="properties.property",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingConciergeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tier",
                    models.CharField(
                        choices=[("quintessential", "Quintessential"), ("signature", "Signature")],
                        default="quintessential",
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("day", "Day"),
                            ("stay", "Stay"),
                            ("event", "Event"),
                            ("hour", "Hour"),
                        ],
                        default="stay",
                        max_length=8,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("delivered", "Delivered"),
                        ],
                        default="requested",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concierge_items",
                        to="reservations.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="pricing.currency",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(max_length=128)),
                ("title", models.CharField(blank=True, max_length=16)),
                ("email", core.fields.CIEmailField(db_index=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("town", models.CharField(blank=True, max_length=128)),
                ("post_code", models.CharField(blank=True, max_length=32)),
                (
                    "contact_method",
                    models.CharField(
                        blank=True,
                        choices=[("email", "Email"), ("phone", "Phone"), ("sms", "SMS")],
                        max_length=8,
                        null=True,
                    ),
                ),
                ("marketing_consent", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("anonymized", "Anonymized"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("anonymized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="properties.country",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guest",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=32, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=128)),
                ("last_name", models.CharField(blank=True, max_length=128)),
                ("email", core.fields.CIEmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("date_from", models.DateField(blank=True, null=True)),
                ("date_to", models.DateField(blank=True, null=True)),
                ("is_flexible", models.BooleanField(default=False)),
                ("adults", models.PositiveSmallIntegerField(default=2)),
                ("children", models.PositiveSmallIntegerField(default=0)),
                ("min_bedrooms", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("availability", "Availability"),
                            ("info", "Info"),
                            ("quote", "Quote"),
                            ("brochure", "Brochure"),
                            ("other", "Other"),
                        ],
                        default="quote",
                        max_length=16,
                    ),
                ),
                ("referral_code", models.CharField(blank=True, max_length=64)),
                (
                    "site_source",
                    models.CharField(
                        choices=[
                            ("main_website", "Main website"),
                            ("agent_portal", "Agent portal"),
                            ("email_inbound", "Inbound email"),
                            ("phone", "Phone"),
                            ("other", "Other"),
                        ],
                        default="main_website",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("quoted", "Quoted"),
                            ("lost", "Lost"),
                            ("converted", "Converted"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("inbound_message", models.TextField(blank=True)),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enquiries_as_agent",
                        to="accounts.contact",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_enquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enquiries",
                        to="properties.property",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enquiries",
                        to="properties.region",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enquiries",
                        to="reservations.guest",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "enquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="guest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="reservations.guest",
            ),
        ),
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=32, unique=True)),
                ("is_unbranded", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("cancel_reason", models.TextField(blank=True)),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotations_as_agent",
                        to="accounts.contact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="pricing.currency",
                    ),
                ),
                (
                    "enquiry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotations",
                        to="reservations.enquiry",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotations",
                        to="reservations.guest",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingHold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("quotation_open", "Quotation open"),
                            ("booking_deposit_pending", "Booking deposit pending"),
                            ("owner_block", "Owner block"),
                            ("maintenance", "Maintenance"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=32,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holds",
                        to="reservations.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holds",
                        to="properties.property",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holds",
                        to="reservations.quotation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuotationLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("adults", models.PositiveSmallIntegerField()),
                ("children", models.PositiveSmallIntegerField(default=0)),
                ("pricing_snapshot", models.JSONField(default=dict)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                ("is_selected", models.BooleanField(default=False)),
                ("is_manual", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotation_lines",
                        to="properties.property",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="reservations.quotation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="quotation_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="reservations.quotationline",
            ),
        ),
        migrations.CreateModel(
            name="TermsVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.CharField(max_length=32, unique=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("body_markdown", models.TextField()),
                ("is_current", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("is_current",),
                        name="only_one_current_terms_version",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="quotation",
            name="terms_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="reservations.termsversion",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="terms_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="reservations.termsversion",
            ),
        ),
        migrations.CreateModel(
            name="BookingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_owner_approval", "Pending owner approval"),
                            ("awaiting_deposit", "Awaiting deposit"),
                            ("deposit_paid", "Deposit paid"),
                            ("awaiting_balance", "Awaiting balance"),
                            ("balance_paid", "Balance paid"),
                            ("checked_in", "Checked in"),
                            ("checked_out", "Checked out"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("declined", "Declined"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_owner_approval", "Pending owner approval"),
                            ("awaiting_deposit", "Awaiting deposit"),
                            ("deposit_paid", "Deposit paid"),
                            ("awaiting_balance", "Awaiting balance"),
                            ("balance_paid", "Balance paid"),
                            ("checked_in", "Checked in"),
                            ("checked_out", "Checked out"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("declined", "Declined"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("owner", "Owner"),
                            ("webhook", "Webhook"),
                            ("system", "System"),
                            ("admin", "Admin"),
                        ],
                        default="user",
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="reservations.booking",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["booking", "created_at"], name="reservation_booking_fceca5_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BookingNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("internal", "Internal"),
                            ("concierge", "Concierge"),
                            ("villa", "Villa"),
                        ],
                        default="general",
                        max_length=16,
                    ),
                ),
                ("body", models.TextField()),
                ("is_pinned", models.BooleanField(default=False)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("staff_only", "Staff only"),
                            ("owner", "Owner"),
                            ("guest", "Guest"),
                        ],
                        default="staff_only",
                        max_length=16,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_collection",
                        to="reservations.booking",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["booking", "created_at"], name="reservation_booking_5c51e0_idx"
                    ),
                    models.Index(fields=["booking", "kind"], name="reservation_booking_d75b10_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EnquiryEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("quoted", "Quoted"),
                            ("lost", "Lost"),
                            ("converted", "Converted"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("quoted", "Quoted"),
                            ("lost", "Lost"),
                            ("converted", "Converted"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("status_change", "Status change"),
                            ("assigned", "Assigned"),
                            ("unassigned", "Unassigned"),
                            ("contacted", "Contacted"),
                            ("quote_sent", "Quote sent"),
                            ("converted", "Converted"),
                            ("lost", "Lost"),
                            ("reopened", "Reopened"),
                            ("note_added", "Note added"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("owner", "Owner"),
                            ("webhook", "Webhook"),
                            ("system", "System"),
                            ("admin", "Admin"),
                        ],
                        default="user",
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="reservations.enquiry",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["enquiry", "created_at"], name="reservation_enquiry_72ea51_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EnquiryNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("internal", "Internal"),
                            ("preferences", "Preferences"),
                        ],
                        default="general",
                        max_length=16,
                    ),
                ),
                ("body", models.TextField()),
                ("is_pinned", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_collection",
                        to="reservations.enquiry",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["enquiry", "created_at"], name="reservation_enquiry_a6dd57_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="guest",
            index=models.Index(
                fields=["status", "last_name", "first_name"], name="reservation_status_ea87ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guest",
            index=models.Index(fields=["email"], name="reservation_email_41e552_idx"),
        ),
        migrations.AddIndex(
            model_name="enquiry",
            index=models.Index(
                fields=["status", "created_at"], name="reservation_status_260787_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enquiry",
            index=models.Index(fields=["email"], name="reservation_email_e6eb6a_idx"),
        ),
        migrations.AddIndex(
            model_name="enquiry",
            index=models.Index(
                fields=["property", "date_from"], name="reservation_propert_ccfa00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookinghold",
            index=models.Index(
                fields=["property", "released_at", "expires_at"],
                name="reservation_propert_cb20a5_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookinghold",
            constraint=models.CheckConstraint(
                condition=models.Q(("date_from__lt", models.F("date_to"))),
                name="bookinghold_date_from_lt_date_to",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookinghold",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quotation__isnull", False),
                    ("booking__isnull", False),
                    ("reason__in", ["owner_block", "maintenance", "manual"]),
                    _connector="OR",
                ),
                name="bookinghold_has_source_or_blocking_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationline",
            constraint=models.CheckConstraint(
                condition=models.Q(("date_from__lt", models.F("date_to"))),
                name="quotationline_date_from_lt_date_to",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_selected", True)),
                fields=("quotation",),
                name="one_selected_line_per_quotation",
            ),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(
                fields=["status", "expires_at"], name="reservation_status_ec9485_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["property", "status", "date_from"], name="reservation_propert_ab58fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["status", "balance_due_at"], name="reservation_status_466633_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["reference"], name="reservation_referen_661cad_idx"),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("date_from__lt", models.F("date_to"))),
                name="booking_date_from_lt_date_to",
            ),
        ),
    ]
