# Generated by Django 5.2.14 on 2026-05-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0002_postgres_exclude_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotationline",
            name="legacy_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
