# Generated by Django 5.2.14 on 2026-05-13 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_contactemail_legacy_id_contactphone_legacy_id"),
        ("pricing", "0005_ratecard_legacy_id_rateplan_legacy_id_and_more"),
        ("properties", "0010_drop_dev_country"),
        ("reservations", "0004_guestpreferencetype_guestpreference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cancelled_at__isnull", True), ("status", "cancelled"), _connector="OR"
                ),
                name="booking_cancelled_at_implies_cancelled_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("archived_at__isnull", True),
                    ("status__in", ("checked_out", "cancelled", "expired", "declined")),
                    _connector="OR",
                ),
                name="booking_archived_at_requires_terminal_status",
            ),
        ),
    ]
