# Generated by Django 5.2.14 on 2026-07-13 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
        ("reservations", "0004_bookingchargeitem_commissionable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="idempotency_key",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("enquiry", "idempotency_key"),
                name="quotation_idempotency_key_unique_per_enquiry",
            ),
        ),
    ]
