# Generated by Django 5.2.14 on 2026-07-13 09:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0004_bookingchargeitem_commissionable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="adjustment",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="discount",
        ),
    ]
