# Generated by Django 5.2.14 on 2026-05-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0005_booking_status_invariants"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinghold",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
