# Generated by Django 5.2.14 on 2026-07-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0006_remove_booking_adjustment_remove_booking_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingchargeitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("cleaning", "Cleaning"),
                    ("pet_fee", "Pet fee"),
                    ("heating", "Heating"),
                    ("linen", "Linen"),
                    ("extra_bed", "Extra bed"),
                    ("service_fee", "Service fee"),
                    ("resort_fee", "Resort fee"),
                    ("damage", "Damage"),
                    ("credit", "Credit"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=16,
            ),
        ),
    ]
