# Generated by Django 5.2.14 on 2026-08-07 08:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
        ("pricing", "0007_extra_idempotency_key_and_more"),
        ("properties", "0004_alter_propertydefaults_prices_entered_as_and_more"),
        ("reservations", "0007_bookingchargeitem_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="deposit_override_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("deposit_override_amount__isnull", True),
                    ("deposit_override_amount__gte", 0),
                    _connector="OR",
                ),
                name="booking_deposit_override_amount_non_negative",
            ),
        ),
    ]
