# Generated by Django 5.2.14 on 2026-05-27 08:46

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0007_booking_overlap_includes_pending_approval"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingGuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("co_traveller", "Co-traveller"),
                            ("payer", "Payer"),
                            ("cc_only", "CC only"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "email_override",
                    core.fields.CIEmailField(blank=True, default="", max_length=254),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_guests",
                        to="reservations.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_guests",
                        to="reservations.guest",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["booking_id", "role", "id"],
                "indexes": [
                    models.Index(fields=["booking", "role"], name="reservation_booking_d40f51_idx"),
                    models.Index(fields=["guest", "role"], name="reservation_guest_i_951b28_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("booking", "guest", "role"),
                        name="bookingguest_unique_booking_guest_role",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("role", "lead")),
                        fields=("booking",),
                        name="bookingguest_one_lead_per_booking",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("role", "payer")),
                        fields=("booking",),
                        name="bookingguest_one_payer_per_booking",
                    ),
                ],
            },
        ),
    ]
