# Generated by Django 5.2.14 on 2026-06-01 22:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_user_preferred_language"),
        ("pricing", "0007_raterule_raterule_poa_excludes_price"),
        ("properties", "0011_hold_duration_hours"),
        ("reservations", "0008_bookingguest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cancelled_at__isnull", False),
                    models.Q(("status", "cancelled"), _negated=True),
                    _connector="OR",
                ),
                name="booking_cancelled_status_requires_cancelled_at",
            ),
        ),
    ]
