# Generated by Django 5.2.14 on 2026-09-02 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_persontag_hnw_owner"),
        ("properties", "0005_alter_propertydescription_section"),
        ("reservations", "0008_booking_deposit_override_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="PastStay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("booking_number", models.CharField(blank=True, max_length=32)),
                ("villa_name", models.CharField(max_length=255)),
                ("destination", models.CharField(blank=True, max_length=255)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="past_stays",
                        to="accounts.person",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="past_stays",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": (
                    models.OrderBy(models.F("year"), descending=True, nulls_last=True),
                    "booking_number",
                ),
                "indexes": [
                    models.Index(fields=["person", "year"], name="paststay_person_year_idx")
                ],
            },
        ),
    ]
