# Generated by Django 5.2.14 on 2026-06-01 22:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0008_bookingguest"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotationline",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
        ),
        migrations.AddField(
            model_name="quotationline",
            name="inclusions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="quotationline",
            name="price_override_reason",
            field=models.TextField(blank=True),
        ),
    ]
