# Generated by Django 5.2.14 on 2026-06-02 04:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0009_quotationline_discount_quotationline_inclusions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotationline",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
