# Generated by Django 5.2.14 on 2026-06-02 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0011_booking_booking_cancelled_status_requires_cancelled_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingServiceCoverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("car", "Car hire"),
                            ("transfers", "Transfers"),
                            ("boat", "Boat"),
                            ("chef", "Chef"),
                            ("grocery", "Grocery"),
                            ("firstnight", "First night"),
                            ("restaurant", "Restaurant"),
                            ("gifting", "Gifting"),
                            ("activities", "Activities"),
                            ("spa", "Spa"),
                            ("wine", "Wine"),
                            ("nanny", "Nanny"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("working_on_it", "Working on it"),
                            ("waiting", "Waiting"),
                            ("arranged_independently", "Arranged independently"),
                            ("not_required", "Not required"),
                            ("done", "Done"),
                        ],
                        default="not_started",
                        max_length=24,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_coverage",
                        to="reservations.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["service"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("booking", "service"), name="uniq_booking_service_coverage"
                    )
                ],
            },
        ),
    ]
