# Generated by Django 5.2.14 on 2026-06-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0011_booking_booking_cancelled_status_requires_cancelled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="number",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        # Concurrency-safe allocator for Quotation.number (legacy QVC/VC parity).
        # No RunPython backfill: dev/staging are reseeded via `seed_dev`, and the
        # legacy import sets number+reference explicitly; `loadlegacy` bumps the
        # high-water mark with setval at the end of the run (see CUTOVER.md).
        #
        # `OWNED BY` ties the sequence's lifecycle to the column, so dropping the
        # column or table reclaims the sequence. The sequence name is mirrored in
        # core.refs.QUOTATION_NUMBER_SEQ (migrations must not import runtime code).
        migrations.RunSQL(
            sql=(
                "CREATE SEQUENCE IF NOT EXISTS quotation_number_seq; "
                "ALTER SEQUENCE quotation_number_seq "
                "OWNED BY reservations_quotation.number;"
            ),
            reverse_sql="DROP SEQUENCE IF EXISTS quotation_number_seq",
        ),
    ]
