# Generated by Django 5.2.14 on 2026-06-02 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0012_bookingservicecoverage"),
        ("reservations", "0012_quotation_number_and_sequence"),
    ]

    operations = []
