# Generated by Django 5.2.14 on 2026-09-16 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_persontag_hnw_owner"),
        ("pricing", "0013_extra_legacy_id"),
        ("properties", "0009_propertyfinance_legacy_id"),
        ("reservations", "0012_booking_house_rules_snapshot_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paststay",
            options={
                "ordering": (
                    models.OrderBy(models.F("year"), descending=True, nulls_last=True),
                    models.OrderBy(models.F("date_from"), descending=True, nulls_last=True),
                    "booking_number",
                )
            },
        ),
        migrations.AddField(
            model_name="paststay",
            name="amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="paststay",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="pricing.currency",
            ),
        ),
        migrations.AddField(
            model_name="paststay",
            name="date_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paststay",
            name="date_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="paststay",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("date_from__isnull", True), ("date_to__isnull", True)),
                    models.Q(
                        ("date_from__isnull", False),
                        ("date_from__lt", models.F("date_to")),
                        ("date_to__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="paststay_date_from_lt_date_to",
            ),
        ),
    ]
