# Generated by Django 5.2.14 on 2026-06-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0013_merge_20260602_1043"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinghold",
            name="reason",
            field=models.CharField(
                choices=[
                    ("quotation_open", "Quotation open"),
                    ("owner_block", "Owner block"),
                    ("maintenance", "Maintenance"),
                    ("manual", "Manual"),
                ],
                default="manual",
                max_length=32,
            ),
        ),
    ]
