# Generated by Django 5.2.14 on 2026-06-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0014_alter_bookinghold_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinghold",
            name="expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
