# Generated by Django 5.2.14 on 2026-06-06 04:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0012_backfill_feature_icons"),
        ("reservations", "0017_rename_owner_block_request"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="ownerblock",
            name="reservation_request_754029_idx",
        ),
        migrations.RenameIndex(
            model_name="ownerblock",
            new_name="reservation_propert_17c4d9_idx",
            old_name="reservation_propert_5f796d_idx",
        ),
        migrations.AddIndex(
            model_name="ownerblock",
            index=models.Index(
                fields=["created_by", "status"], name="reservation_created_88b6bd_idx"
            ),
        ),
    ]
