# Generated by Django 5.2.14 on 2026-06-08 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0014_propertycalendarfeed"),
        ("reservations", "0022_quotation_requires_enquiry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ownerblock",
            name="idempotency_key",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="ownerblock",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manual"), ("ical", "iCal feed")],
                default="manual",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="ownerblock",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owner_block_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="ownerblock",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source", "ical"), ("created_by__isnull", False), _connector="OR"
                ),
                name="ownerblock_manual_requires_creator",
            ),
        ),
        migrations.AddConstraint(
            model_name="ownerblock",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status", "approved"), models.Q(("idempotency_key", ""), _negated=True)
                ),
                fields=("property", "idempotency_key"),
                name="unique_active_ical_block_per_property_key",
            ),
        ),
    ]
