# Generated by Django 5.2.14 on 2026-06-09 06:59

import django.db.models.functions.comparison
import django.db.models.functions.datetime
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0023_ownerblock_idempotency_key_ownerblock_source_and_more"),
    ]

    operations = [
        # Reference allocator (BUG-007). The column's `db_default` calls
        # `nextval('enquiry_reference_seq')`, so the sequence must exist first.
        # `OWNED BY` ties its lifecycle to the column. The name mirrors the
        # model's `reference_db_default(... sequence="enquiry_reference_seq")`
        # (migrations must not import app runtime code, so it's repeated here).
        migrations.RunSQL(
            sql=(
                "CREATE SEQUENCE IF NOT EXISTS enquiry_reference_seq; "
                "ALTER SEQUENCE enquiry_reference_seq OWNED BY reservations_enquiry.reference;"
            ),
            reverse_sql="DROP SEQUENCE IF EXISTS enquiry_reference_seq",
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="reference",
            field=models.CharField(
                db_default=django.db.models.functions.text.Concat(
                    models.Value("E-"),
                    django.db.models.functions.comparison.Cast(
                        django.db.models.functions.datetime.ExtractYear(
                            django.db.models.functions.datetime.Now()
                        ),
                        output_field=models.CharField(),
                    ),
                    models.Value("-"),
                    django.db.models.functions.comparison.Cast(
                        models.Func(
                            models.Value("enquiry_reference_seq"),
                            function="nextval",
                            output_field=models.BigIntegerField(),
                        ),
                        output_field=models.CharField(),
                    ),
                    output_field=models.CharField(),
                ),
                max_length=32,
                unique=True,
            ),
        ),
    ]
