# Generated by Django 5.2.14 on 2026-06-09 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0024_alter_enquiry_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinghold",
            name="quotation_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="holds",
                to="reservations.quotationline",
            ),
        ),
    ]
