# Generated by Django 5.2.14 on 2026-06-10 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_user_preferred_language"),
        ("pricing", "0010_remove_raterule_priority"),
        ("properties", "0016_alter_property_options"),
        ("reservations", "0028_bookingchargeitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                fields=("quotation_line",), name="booking_one_per_quotation_line"
            ),
        ),
    ]
