# Generated by Django 5.2.14 on 2026-06-11 10:11
"""Add Enquiry.flexibility_days (the structured "± N days" spread).

Pre-existing rows keep their stored dates with flexibility_days=0. Under the
old form behaviour the spread was applied destructively to date_from/date_to
on submit, so those rows hold already-widened dates and the original requested
dates are unrecoverable — accepted; no backfill is possible.
"""

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0029_booking_booking_one_per_quotation_line"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="flexibility_days",
            field=models.PositiveSmallIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(3)]
            ),
        ),
    ]
