# Generated by Django 5.2.14 on 2026-06-18 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_rename_person_status_index"),
        ("reservations", "0030_enquiry_flexibility_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings_as_agent",
                to="accounts.person",
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enquiries_as_agent",
                to="accounts.person",
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotations_as_agent",
                to="accounts.person",
            ),
        ),
    ]
