# Generated by Django 5.2.14 on 2026-06-18 18:39

from django.db import migrations, models

# Stage value rename to the operator-facing dashboard vocabulary (GAP-038/039).
# `new`/`converted` are unchanged; `follow_up` is net-new (added in a later
# migration, so it has no rows to rewrite here).
_RENAMES = {
    "contacted": "progressing",
    "quoted": "quote_sent",
    "lost": "dead",
}
_REVERSE = {new: old for old, new in _RENAMES.items()}


def _rewrite(apps, mapping):
    """Rewrite the three stage-bearing columns in place.

    These are bulk `.update()`s by design: the rename is a point-in-time
    relabel, not a domain event, so it must not fire state-machine or audit
    signals. Historical `core.AuditLog` JSON keeps the pre-rename strings.
    """
    Enquiry = apps.get_model("reservations", "Enquiry")
    EnquiryEvent = apps.get_model("reservations", "EnquiryEvent")
    for old, new in mapping.items():
        Enquiry.objects.filter(status=old).update(status=new)
        EnquiryEvent.objects.filter(from_status=old).update(from_status=new)
        EnquiryEvent.objects.filter(to_status=old).update(to_status=new)


def forwards(apps, schema_editor):
    _rewrite(apps, _RENAMES)


def backwards(apps, schema_editor):
    _rewrite(apps, _REVERSE)


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0031_alter_booking_agent_alter_enquiry_agent_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="enquiry",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("progressing", "Progressing"),
                    ("quote_sent", "Quote sent"),
                    ("dead", "Dead"),
                    ("converted", "Converted"),
                ],
                default="new",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="enquiryevent",
            name="from_status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("progressing", "Progressing"),
                    ("quote_sent", "Quote sent"),
                    ("dead", "Dead"),
                    ("converted", "Converted"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="enquiryevent",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("progressing", "Progressing"),
                    ("quote_sent", "Quote sent"),
                    ("dead", "Dead"),
                    ("converted", "Converted"),
                ],
                max_length=16,
            ),
        ),
    ]
