# Generated by Django 5.2.14 on 2026-06-18 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_person_country_person_marketing_consent_and_more"),
        ("reservations", "0031_alter_booking_agent_alter_enquiry_agent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings_as_customer",
                to="accounts.person",
            ),
        ),
        migrations.AddField(
            model_name="bookingguest",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="booking_guests",
                to="accounts.person",
            ),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enquiries_as_customer",
                to="accounts.person",
            ),
        ),
        migrations.AddField(
            model_name="guestpreference",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="travel_preferences",
                to="accounts.person",
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotations_as_customer",
                to="accounts.person",
            ),
        ),
    ]
