# Generated by Django 5.2.14 on 2026-06-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0032_rename_enquiry_stage_vocab"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("progressing", "Progressing"),
                    ("quote_sent", "Quote sent"),
                    ("follow_up", "Follow-up"),
                    ("dead", "Dead"),
                    ("converted", "Converted"),
                ],
                default="new",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="enquiryevent",
            name="from_status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("progressing", "Progressing"),
                    ("quote_sent", "Quote sent"),
                    ("follow_up", "Follow-up"),
                    ("dead", "Dead"),
                    ("converted", "Converted"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="enquiryevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("status_change", "Status change"),
                    ("assigned", "Assigned"),
                    ("unassigned", "Unassigned"),
                    ("contacted", "Contacted"),
                    ("quote_sent", "Quote sent"),
                    ("follow_up", "Follow-up"),
                    ("converted", "Converted"),
                    ("lost", "Lost"),
                    ("reopened", "Reopened"),
                    ("note_added", "Note added"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="enquiryevent",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("progressing", "Progressing"),
                    ("quote_sent", "Quote sent"),
                    ("follow_up", "Follow-up"),
                    ("dead", "Dead"),
                    ("converted", "Converted"),
                ],
                max_length=16,
            ),
        ),
    ]
