# Generated by Django 5.2.14 on 2026-06-18 19:56
#
# GAP-045 Unit 3d-A: make `person` the authoritative customer FK (NOT NULL on the
# four always-customer models), relax `guest` to nullable, and repoint the two
# guest-keyed constraints + the guest index onto `person`. The RunPython safety
# backfill below links any straggler `person IS NULL` row (created between 0033
# and the 3c write-cutover) from its `guest-{pk}` Person mirror, so the NOT-NULL
# flips cannot trip. Frozen (no `person_sync` import) — migrations must not import
# mutable app code. Fail-closed by design: a row that still has no person after
# the backfill (a genuine orphan) aborts the next AlterField rather than being
# silently NULLed.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# The four models flipping `person` → NOT NULL (Enquiry stays nullable).
_PERSON_FK_MODELS = ("Booking", "BookingGuest", "GuestPreference", "Quotation")


def _backfill_person(apps, schema_editor):
    """Fill any null `person` from the row's guest mirror (legacy_id=guest-{pk})."""
    Person = apps.get_model("accounts", "Person")
    mirror_by_guest: dict[int, int] = {}
    for legacy_id, pk in Person.objects.filter(legacy_id__startswith="guest-").values_list(
        "legacy_id", "pk"
    ):
        suffix = legacy_id[len("guest-") :]
        if suffix.isdigit():
            mirror_by_guest[int(suffix)] = pk
    for model_name in _PERSON_FK_MODELS:
        model = apps.get_model("reservations", model_name)
        to_update = []
        for row in model.objects.filter(person__isnull=True, guest__isnull=False).only(
            "pk", "guest_id"
        ):
            person_pk = mirror_by_guest.get(row.guest_id)
            if person_pk is not None:
                row.person_id = person_pk
                to_update.append(row)
        if to_update:
            model.objects.bulk_update(to_update, ["person_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_person_country_person_marketing_consent_and_more"),
        ("reservations", "0033_backfill_person_from_guest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_backfill_person, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name="guestpreference",
            options={"ordering": ["person_id", "preference_type_id"]},
        ),
        migrations.RemoveConstraint(
            model_name="bookingguest",
            name="bookingguest_unique_booking_guest_role",
        ),
        migrations.RemoveConstraint(
            model_name="guestpreference",
            name="unique_guest_preference",
        ),
        migrations.RemoveIndex(
            model_name="bookingguest",
            name="reservation_guest_i_951b28_idx",
        ),
        migrations.AlterField(
            model_name="booking",
            name="guest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="reservations.guest",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings_as_customer",
                to="accounts.person",
            ),
        ),
        migrations.AlterField(
            model_name="bookingguest",
            name="guest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="booking_guests",
                to="reservations.guest",
            ),
        ),
        migrations.AlterField(
            model_name="bookingguest",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="booking_guests",
                to="accounts.person",
            ),
        ),
        migrations.AlterField(
            model_name="guestpreference",
            name="guest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preferences",
                to="reservations.guest",
            ),
        ),
        migrations.AlterField(
            model_name="guestpreference",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="travel_preferences",
                to="accounts.person",
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="guest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotations",
                to="reservations.guest",
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotations_as_customer",
                to="accounts.person",
            ),
        ),
        migrations.AddIndex(
            model_name="bookingguest",
            index=models.Index(fields=["person", "role"], name="reservation_person__8b28ce_idx"),
        ),
        migrations.AddConstraint(
            model_name="bookingguest",
            constraint=models.UniqueConstraint(
                fields=("booking", "person", "role"), name="bookingguest_unique_booking_person_role"
            ),
        ),
        migrations.AddConstraint(
            model_name="guestpreference",
            constraint=models.UniqueConstraint(
                fields=("person", "preference_type", "quotation"), name="unique_person_preference"
            ),
        ),
    ]
