# Generated by Django 5.2.14 on 2026-06-18 19:08

from django.conf import settings
from django.db import migrations, models


def backfill_lost_reason(apps, schema_editor):
    """Existing DEAD enquiries have no structured reason — set UNKNOWN so the
    dead-requires-lost-reason constraint added next holds for every row."""
    Enquiry = apps.get_model("reservations", "Enquiry")
    Enquiry.objects.filter(status="dead", lost_reason="").update(lost_reason="unknown")


def noop(apps, schema_editor):
    """Reverse is a no-op: dropping the field/constraint (the surrounding
    operations) is what undoes this; blanking the values is unnecessary."""


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_rename_person_status_index"),
        ("properties", "0019_merge_20260618_1201"),
        ("reservations", "0033_add_follow_up_stage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="lost_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("found_alternative", "Found alternative"),
                    ("availability", "Availability"),
                    ("different_destination", "Different destination"),
                    ("no_group_consensus", "No group consensus"),
                    ("unknown", "Unknown"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.RunPython(backfill_lost_reason, noop),
        migrations.AddConstraint(
            model_name="enquiry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "dead"), _negated=True),
                    models.Q(("lost_reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="enquiry_dead_requires_lost_reason",
            ),
        ),
    ]
