# Generated by Django 5.2.14 on 2026-06-18 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_rename_person_status_index"),
        ("properties", "0019_merge_20260618_1201"),
        ("reservations", "0034_enquiry_lost_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="lead_status",
            field=models.CharField(
                choices=[("hot", "Hot"), ("warm", "Warm"), ("cold", "Cold"), ("dead", "Dead")],
                default="warm",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="enquiryevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("status_change", "Status change"),
                    ("assigned", "Assigned"),
                    ("unassigned", "Unassigned"),
                    ("contacted", "Contacted"),
                    ("quote_sent", "Quote sent"),
                    ("follow_up", "Follow-up"),
                    ("converted", "Converted"),
                    ("lost", "Lost"),
                    ("reopened", "Reopened"),
                    ("note_added", "Note added"),
                    ("lead_status_changed", "Lead status changed"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddIndex(
            model_name="enquiry",
            index=models.Index(
                fields=["lead_status", "status"], name="reservation_lead_st_c08021_idx"
            ),
        ),
    ]
