# Generated by Django 5.2.14 on 2026-06-22 09:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0035_enquiry_lead_status"),
        ("reservations", "0035_remove_guestpreference_guest_remove_booking_guest_and_more"),
    ]

    operations = []
