# Generated by Django 5.2.14 on 2026-06-23 08:33

import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.datetime
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0010_remove_raterule_priority"),
        ("reservations", "0036_merge_20260622_0934"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Reference allocator (BUG-007 pattern). The `reference` column's
        # `db_default` below calls `nextval('damage_claim_reference_seq')`, so
        # the sequence must exist before the model is created; `OWNED BY` (after
        # CreateModel, once the table exists) ties its lifecycle to the column.
        # The name is mirrored in the model's
        # `reference_db_default(... sequence="damage_claim_reference_seq")`
        # (migrations must not import app runtime code, so it's repeated here).
        migrations.RunSQL(
            sql="CREATE SEQUENCE IF NOT EXISTS damage_claim_reference_seq;",
            reverse_sql="DROP SEQUENCE IF EXISTS damage_claim_reference_seq;",
        ),
        migrations.CreateModel(
            name="DamageClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        db_default=django.db.models.functions.text.Concat(
                            models.Value("DC-"),
                            django.db.models.functions.comparison.Cast(
                                django.db.models.functions.datetime.ExtractYear(
                                    django.db.models.functions.datetime.Now()
                                ),
                                output_field=models.CharField(),
                            ),
                            models.Value("-"),
                            django.db.models.functions.comparison.Cast(
                                models.Func(
                                    models.Value("damage_claim_reference_seq"),
                                    function="nextval",
                                    output_field=models.BigIntegerField(),
                                ),
                                output_field=models.CharField(),
                            ),
                            output_field=models.CharField(),
                        ),
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("approved", "Approved"),
                            ("settled", "Settled"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("itemized_lines", models.JSONField(blank=True, default=list)),
                ("photos", models.JSONField(blank=True, default=list)),
                ("accepted_by_guest_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="damage_claims",
                        to="reservations.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="pricing.currency",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["booking", "status"], name="reservation_booking_9180c6_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)), name="damage_claim_amount_positive"
                    )
                ],
            },
        ),
        migrations.RunSQL(
            sql=(
                "ALTER SEQUENCE damage_claim_reference_seq "
                "OWNED BY reservations_damageclaim.reference;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
