# Generated by Django 5.2.14 on 2026-07-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0038_remove_damageclaim_photos_damageclaimphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinghold",
            name="legacy_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
