# Generated by Django 5.2.14 on 2026-05-12 21:47

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=16)),
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(max_length=128)),
                ("company", models.CharField(blank=True, max_length=128)),
                ("website_url", models.URLField(blank=True)),
                (
                    "preferred_method",
                    models.CharField(
                        choices=[("email", "Email"), ("phone", "Phone"), ("sms", "SMS")],
                        default="email",
                        max_length=8,
                    ),
                ),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("anonymized", "Anonymized"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("anonymized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="ContactEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", core.fields.CIEmailField(max_length=254)),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("work", "Work"),
                            ("personal", "Personal"),
                            ("other", "Other"),
                        ],
                        default="primary",
                        max_length=16,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="accounts.contact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=32)),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("mobile", "Mobile"),
                            ("work", "Work"),
                            ("home", "Home"),
                            ("fax", "Fax"),
                            ("other", "Other"),
                        ],
                        default="mobile",
                        max_length=16,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to="accounts.contact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("session_key", models.CharField(max_length=40, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["status", "last_name", "first_name"], name="accounts_co_status_9527de_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contactemail",
            constraint=models.UniqueConstraint(
                fields=("contact", "email"), name="unique_contact_email"
            ),
        ),
        migrations.AddConstraint(
            model_name="contactemail",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("contact",),
                name="one_primary_email_per_contact",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactphone",
            constraint=models.UniqueConstraint(
                fields=("contact", "number"), name="unique_contact_phone"
            ),
        ),
        migrations.AddConstraint(
            model_name="contactphone",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("contact",),
                name="one_primary_phone_per_contact",
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "last_seen_at"], name="accounts_us_user_id_8ce1d9_idx"
            ),
        ),
    ]
