# Generated by Django 5.2.14 on 2026-07-08 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="properties.country",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agents",
                to="accounts.organisation",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="properties.country",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="personemail",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="accounts.person",
            ),
        ),
        migrations.AddField(
            model_name="personphone",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phones",
                to="accounts.person",
            ),
        ),
        migrations.AddField(
            model_name="personrelationship",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="personrelationship",
            name="from_person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationships_out",
                to="accounts.person",
            ),
        ),
        migrations.AddField(
            model_name="personrelationship",
            name="to_person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationships_in",
                to="accounts.person",
            ),
        ),
        migrations.AddField(
            model_name="personrelationship",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="organisation",
            index=models.Index(fields=["status", "name"], name="accounts_or_status_47dd66_idx"),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["status", "last_name", "first_name"], name="accounts_pe_status_03fafd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="personemail",
            constraint=models.UniqueConstraint(
                fields=("contact", "email"), name="unique_contact_email"
            ),
        ),
        migrations.AddConstraint(
            model_name="personemail",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("contact",),
                name="one_primary_email_per_contact",
            ),
        ),
        migrations.AddConstraint(
            model_name="personphone",
            constraint=models.UniqueConstraint(
                fields=("contact", "number"), name="unique_contact_phone"
            ),
        ),
        migrations.AddConstraint(
            model_name="personphone",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("contact",),
                name="one_primary_phone_per_contact",
            ),
        ),
        migrations.AddIndex(
            model_name="personrelationship",
            index=models.Index(
                fields=["from_person", "kind"], name="accounts_pe_from_pe_a79e2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personrelationship",
            index=models.Index(fields=["to_person", "kind"], name="accounts_pe_to_pers_65d7d6_idx"),
        ),
        migrations.AddConstraint(
            model_name="personrelationship",
            constraint=models.UniqueConstraint(
                fields=("from_person", "to_person", "kind"),
                name="personrelationship_unique_from_to_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="personrelationship",
            constraint=models.CheckConstraint(
                condition=models.Q(("from_person", models.F("to_person")), _negated=True),
                name="personrelationship_no_self_link",
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "last_seen_at"], name="accounts_us_user_id_8ce1d9_idx"
            ),
        ),
    ]
