# Generated by Django 5.2.14 on 2026-05-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_contact_contactemail_contactphone_usersession_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="legacy_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
