# Generated by Django 5.2.14 on 2026-05-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_contactemail_legacy_id_contactphone_legacy_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(default="en", max_length=8),
        ),
    ]
