# Generated by Django 5.2.14 on 2026-06-18 06:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_rename_contact_to_person"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="person",
            new_name="accounts_pe_status_03fafd_idx",
            old_name="accounts_co_status_9527de_idx",
        ),
    ]
