# Generated by Django 5.2.14 on 2026-06-18 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_rename_person_status_index"),
        ("properties", "0017_alter_groupfinance_contact_alter_property_contacts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="properties.country",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="marketing_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person",
            name="post_code",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="person",
            name="town",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
