# Generated by Django 5.2.14 on 2026-06-19 12:10

from django.db import migrations, models

# GAP-045 D2: customer mirrors are the `guest-`-prefixed Persons (the only
# customer-origin marker until D5 re-keys them). Frozen literal — migrations must
# not import mutable app code. Mirror of accounts.models.GUEST_LEGACY_PREFIX.
_GUEST_LEGACY_PREFIX = "guest-"


def _backfill_kind(apps, schema_editor):
    """Classify existing Persons: `guest-` mirrors are CUSTOMER, the rest keep the
    CONTACT default. Bulk `.update()` bypasses the audit signal — acceptable for a
    one-shot backfill (same precedent as reservations/0033)."""
    Person = apps.get_model("accounts", "Person")
    Person.objects.filter(legacy_id__startswith=_GUEST_LEGACY_PREFIX).update(kind="customer")


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_person_country_person_marketing_consent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="kind",
            field=models.CharField(
                choices=[("customer", "Customer"), ("contact", "Contact")],
                default="contact",
                max_length=16,
            ),
        ),
        migrations.RunPython(_backfill_kind, migrations.RunPython.noop),
    ]
