# Generated by Django 5.2.14 on 2026-06-22 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_organisation"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agents",
                to="accounts.organisation",
            ),
        ),
    ]
