# Generated by Django 5.2.14 on 2026-06-23 07:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_drop_person_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("vip", "VIP"),
                        ("trade", "Trade"),
                        ("pa", "PA"),
                        ("nicks_friend", "Nick's friend"),
                        ("nicks_network", "Nick's network"),
                        ("disability", "Disability"),
                        ("approach_with_care", "Approach with care"),
                        ("past_issues", "Past issues"),
                        ("specific_preferences", "Specific preferences"),
                        ("time_waster", "Time waster"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
