# Generated by Django 5.2.14 on 2026-06-23 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_person_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("spouse", "Spouse"),
                            ("partner", "Partner"),
                            ("child", "Child"),
                            ("parent", "Parent"),
                            ("pa", "PA"),
                            ("sibling", "Sibling"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_out",
                        to="accounts.person",
                    ),
                ),
                (
                    "to_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_in",
                        to="accounts.person",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["from_person_id", "id"],
                "indexes": [
                    models.Index(
                        fields=["from_person", "kind"], name="accounts_pe_from_pe_a79e2e_idx"
                    ),
                    models.Index(
                        fields=["to_person", "kind"], name="accounts_pe_to_pers_65d7d6_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_person", "to_person", "kind"),
                        name="personrelationship_unique_from_to_kind",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("from_person", models.F("to_person")), _negated=True),
                        name="personrelationship_no_self_link",
                    ),
                ],
            },
        ),
    ]
