# Generated by Django 5.2.14 on 2026-07-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_person_name_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tfa_last_verified_step",
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
    ]
