# Generated by Django 5.2.14 on 2026-07-08 11:54

import core.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SmtpProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "scope",
                    models.CharField(
                        choices=[("system", "System"), ("personal", "Personal")], max_length=16
                    ),
                ),
                ("host", models.CharField(max_length=255)),
                ("port", models.PositiveSmallIntegerField()),
                ("username", models.CharField(max_length=255)),
                ("encrypted_password", core.fields.EncryptedTextField(blank=True, default="")),
                ("use_tls", models.BooleanField(default=True)),
                ("from_email", models.EmailField(max_length=254)),
                ("reply_to", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="smtp_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("template_key", models.CharField(max_length=64)),
                ("template_version", models.PositiveIntegerField()),
                ("to", models.JSONField(default=list)),
                ("cc", models.JSONField(default=list)),
                ("bcc", models.JSONField(default=list)),
                ("from_email", models.EmailField(max_length=254)),
                ("rendered_subject", models.TextField()),
                ("rendered_body", models.TextField()),
                ("rendered_body_html", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                            ("blocked", "Blocked"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("provider_reference", models.CharField(blank=True, max_length=255)),
                ("failure_reason", models.TextField(blank=True)),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("correlation", models.JSONField(blank=True, default=dict)),
                ("idempotency_hash", models.CharField(blank=True, db_index=True, max_length=64)),
                ("queued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sender_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_email_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "smtp_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="comms.smtpprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=255)),
                ("version", models.PositiveIntegerField(default=1)),
                ("subject_template", models.TextField()),
                ("body_template_mjml", models.TextField(blank=True)),
                ("body_template_html", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["key", "is_active"], name="comms_email_key_82bc3f_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "version"), name="unique_template_version"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("key",),
                        name="one_active_template_per_key",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="smtpprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("owner__isnull", False), ("scope", "personal")),
                    models.Q(("owner__isnull", True), ("scope", "system")),
                    _connector="OR",
                ),
                name="smtp_profile_owner_matches_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="smtpprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("scope", "system")),
                fields=("scope",),
                name="one_active_system_smtp_profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="smtpprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("scope", "personal")),
                fields=("owner",),
                name="one_active_personal_profile_per_user",
            ),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(
                fields=["status", "queued_at"], name="comms_email_status_3d4f83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(
                fields=["template_key", "queued_at"], name="comms_email_templat_2b51a1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="emaillog",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_hash", ""), _negated=True),
                fields=("idempotency_hash",),
                name="unique_email_log_idempotency_hash",
            ),
        ),
    ]
