# Generated by Django 5.2.14 on 2026-05-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillog",
            name="rendered_body_html",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="body_template_html",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="body_template_mjml",
            field=models.TextField(blank=True),
        ),
    ]
