# Generated by Django 5.2.14 on 2026-05-25 22:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comms", "0006_seed_reminder_templates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="emaillog",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_hash", ""), _negated=True),
                fields=("idempotency_hash",),
                name="unique_email_log_idempotency_hash",
            ),
        ),
    ]
