# Generated by Django 5.2.14 on 2026-05-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comms", "0008_seed_card_update_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("bounced", "Bounced"),
                    ("blocked", "Blocked"),
                ],
                default="queued",
                max_length=16,
            ),
        ),
    ]
