# Generated by Django 5.2.14 on 2026-05-12 21:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _upload_ticket_default_expires_at():
    """Inlined from the deleted `core.models.upload` (UploadTicket is dropped
    in 0005); kept so this historical migration stays importable."""
    from datetime import timedelta

    from django.utils import timezone

    return timezone.now() + timedelta(hours=1)


def _idempotency_default_expires_at():
    """Inlined from the deleted `core.models.idempotency` (IdempotencyRecord is
    dropped in 0006); kept so this historical migration stays importable."""
    from datetime import timedelta

    from django.utils import timezone

    return timezone.now() + timedelta(hours=24)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("path", models.CharField(max_length=512)),
                ("key", models.CharField(max_length=512, unique=True)),
                ("content_type", models.CharField(blank=True, max_length=128)),
                ("max_bytes", models.PositiveIntegerField(default=0)),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, default=_upload_ticket_default_expires_at),
                ),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="upload_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("object_id", models.CharField(max_length=64)),
                ("field_diffs", models.JSONField(default=dict)),
                ("correlation_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="contenttypes.contenttype"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "created_at"],
                        name="core_auditl_content_e3f5a7_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"], name="core_auditl_actor_i_41600a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=128)),
                ("method", models.CharField(max_length=8)),
                ("path", models.CharField(max_length=512)),
                ("request_hash", models.CharField(max_length=64)),
                ("response_status", models.PositiveSmallIntegerField()),
                ("response_body", models.JSONField()),
                ("response_headers", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, default=_idempotency_default_expires_at),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="idempotency_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "path", "key"), name="unique_idempotency_key_per_user_path"
                    )
                ],
            },
        ),
    ]
