# Generated by Django 5.2.14 on 2026-06-10 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_postgres_extensions"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UploadTicket",
        ),
    ]
