# Generated by Django 5.2.14 on 2026-07-01 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_drop_uploadticket"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IdempotencyRecord",
        ),
    ]
