# Generated by Django 5.2.14 on 2026-05-12 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(max_length=64)),
                ("symbol", models.CharField(blank=True, max_length=8)),
                ("decimal_places", models.PositiveSmallIntegerField(default=2)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "currencies",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Extra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cleaning", "Cleaning"),
                            ("pet_fee", "Pet fee"),
                            ("heating", "Heating"),
                            ("linen", "Linen"),
                            ("extra_bed", "Extra bed"),
                            ("service_fee", "Service fee"),
                            ("resort_fee", "Resort fee"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "calc",
                    models.CharField(
                        choices=[
                            ("fixed_per_stay", "Fixed per stay"),
                            ("fixed_per_night", "Fixed per night"),
                            ("fixed_per_person", "Fixed per person"),
                            ("fixed_per_person_per_night", "Fixed per person per night"),
                            ("percent_of_subtotal", "Percent of subtotal"),
                        ],
                        max_length=32,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_mandatory", models.BooleanField(default=True)),
                ("applies_from", models.DateField(blank=True, null=True)),
                ("applies_to", models.DateField(blank=True, null=True)),
                ("min_party", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_party", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["property", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="FxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rate", models.DecimalField(decimal_places=8, max_digits=18)),
                ("as_of", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="RateCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("min_nights", models.PositiveSmallIntegerField(default=1)),
                ("max_nights", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("changeover_weekday", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["plan", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="RatePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "price_basis",
                    models.CharField(
                        choices=[("gross", "Gross"), ("net", "Net")], default="gross", max_length=8
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("inclusion", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["property", "-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="RateRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("min_party", models.PositiveSmallIntegerField(default=1)),
                ("max_party", models.PositiveSmallIntegerField()),
                ("priority", models.PositiveSmallIntegerField(default=0)),
                (
                    "nightly",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "weekly",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("is_poa", models.BooleanField(default=False)),
                ("is_locked", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["card", "-priority", "date_from"],
            },
        ),
        migrations.CreateModel(
            name="VillaPricingSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "min_nightly",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "max_nightly",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "min_weekly",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "max_weekly",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("next_available_date", models.DateField(blank=True, null=True)),
                ("min_party", models.PositiveSmallIntegerField(default=1)),
                ("max_party", models.PositiveSmallIntegerField(default=1)),
                ("rebuilt_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "villa pricing summary",
                "verbose_name_plural": "villa pricing summaries",
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("code", models.CharField(blank=True, max_length=64, null=True, unique=True)),
                (
                    "rule_kind",
                    models.CharField(
                        choices=[
                            ("length_of_stay", "Length of stay"),
                            ("early_bird", "Early bird"),
                            ("last_minute", "Last minute"),
                            ("repeat_guest", "Repeat guest"),
                            ("promo_code", "Promo code"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("percent", "Percent"), ("fixed", "Fixed")], max_length=8
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("min_nights", models.PositiveSmallIntegerField(default=0)),
                ("threshold_days", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField()),
                ("max_uses", models.PositiveIntegerField(blank=True, null=True)),
                ("uses_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["property", "name"],
            },
        ),
    ]
