# Generated by Django 5.2.14 on 2026-07-08 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pricing", "0001_initial"),
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discounts",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="extra",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="extra",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="extras",
                to="pricing.currency",
            ),
        ),
        migrations.AddField(
            model_name="extra",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extras",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="extra",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fxrate",
            name="base",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fx_rates_as_base",
                to="pricing.currency",
            ),
        ),
        migrations.AddField(
            model_name="fxrate",
            name="quote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fx_rates_as_quote",
                to="pricing.currency",
            ),
        ),
        migrations.AddField(
            model_name="rateband",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rateband",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rateperiod",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rateperiod",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rateband",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bands",
                to="pricing.rateperiod",
            ),
        ),
        migrations.AddField(
            model_name="rateplan",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rateplan",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rate_plans",
                to="pricing.currency",
            ),
        ),
        migrations.AddField(
            model_name="rateplan",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rate_plans",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="rateplan",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rateperiod",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periods",
                to="pricing.rateplan",
            ),
        ),
        migrations.AddField(
            model_name="villapricingsummary",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pricing_summaries",
                to="pricing.currency",
            ),
        ),
        migrations.AddField(
            model_name="villapricingsummary",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricing_summaries",
                to="properties.property",
            ),
        ),
        migrations.AddIndex(
            model_name="discount",
            index=models.Index(
                fields=["property", "is_active"], name="pricing_dis_propert_3ad4de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discount",
            index=models.Index(fields=["code"], name="pricing_dis_code_2dade6_idx"),
        ),
        migrations.AddIndex(
            model_name="extra",
            index=models.Index(
                fields=["property", "is_active", "sort_order"],
                name="pricing_ext_propert_4a6321_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="extra",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("applies_from__isnull", True),
                    ("applies_to__isnull", True),
                    ("applies_from__lte", models.F("applies_to")),
                    _connector="OR",
                ),
                name="extra_applies_from_lte_applies_to",
            ),
        ),
        migrations.AddConstraint(
            model_name="extra",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("min_party__isnull", True),
                    ("max_party__isnull", True),
                    ("min_party__lte", models.F("max_party")),
                    _connector="OR",
                ),
                name="extra_min_party_lte_max_party",
            ),
        ),
        migrations.AddIndex(
            model_name="fxrate",
            index=models.Index(
                fields=["base", "quote", "-as_of"], name="pricing_fxr_base_id_784544_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fxrate",
            constraint=models.UniqueConstraint(
                fields=("base", "quote", "as_of"), name="fxrate_unique_base_quote_as_of"
            ),
        ),
        migrations.AddIndex(
            model_name="rateband",
            index=models.Index(
                fields=["period", "min_party"], name="pricing_rat_period__49f1f2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rateband",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_party__lte", models.F("max_party"))),
                name="rateband_min_party_lte_max_party",
            ),
        ),
        migrations.AddConstraint(
            model_name="rateband",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("nightly__isnull", False),
                    ("weekly__isnull", False),
                    ("is_poa", True),
                    _connector="OR",
                ),
                name="rateband_has_price_or_poa",
            ),
        ),
        migrations.AddConstraint(
            model_name="rateband",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_poa", False),
                    models.Q(("nightly__isnull", True), ("weekly__isnull", True)),
                    _connector="OR",
                ),
                name="rateband_poa_excludes_price",
            ),
        ),
        migrations.AddIndex(
            model_name="rateplan",
            index=models.Index(
                fields=["property", "currency", "is_active"], name="pricing_rat_propert_8be37b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rateplan",
            index=models.Index(
                fields=["effective_from", "effective_to"], name="pricing_rat_effecti_1aaf7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rateperiod",
            index=models.Index(
                fields=["plan", "date_from", "date_to"], name="pricing_rat_plan_id_54dd48_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rateperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("date_from__lte", models.F("date_to"))),
                name="rateperiod_date_from_lte_date_to",
            ),
        ),
        migrations.AddConstraint(
            model_name="rateperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True), name="rateperiod_name_not_blank"
            ),
        ),
        migrations.AddConstraint(
            model_name="villapricingsummary",
            constraint=models.UniqueConstraint(
                fields=("property", "currency"), name="pricingsummary_unique_property_currency"
            ),
        ),
    ]
