# Generated by Django 5.2.14 on 2026-05-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0003_raterule_exclude_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="legacy_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
