# Generated by Django 5.2.14 on 2026-05-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0004_currency_legacy_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratecard",
            name="legacy_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="rateplan",
            name="legacy_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="raterule",
            name="legacy_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
