# Generated by Django 5.2.14 on 2026-07-12 07:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0004_extra_commissionable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rateband",
            name="reduced_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rateband",
            name="reduced_nightly",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="rateband",
            name="reduced_weekly",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="rateband",
            name="reduction_percent",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="rateband",
            name="reduction_reason",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name="rateband",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reduction_percent__isnull", True),
                    models.Q(("reduction_percent__gt", 0), ("reduction_percent__lt", 100)),
                    _connector="OR",
                ),
                name="rateband_reduction_percent_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="rateband",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reduction_percent__isnull", True),
                    models.Q(("reduced_nightly__isnull", True), ("reduced_weekly__isnull", True)),
                    _connector="OR",
                ),
                name="rateband_reduction_percent_excludes_fixed",
            ),
        ),
        migrations.AddConstraint(
            model_name="rateband",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reduced_nightly__isnull", True),
                    models.Q(
                        ("nightly__isnull", False),
                        ("reduced_nightly__gt", 0),
                        ("reduced_nightly__lt", models.F("nightly")),
                    ),
                    _connector="OR",
                ),
                name="rateband_reduced_nightly_lt_base",
            ),
        ),
        migrations.AddConstraint(
            model_name="rateband",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reduced_weekly__isnull", True),
                    models.Q(
                        ("weekly__isnull", False),
                        ("reduced_weekly__gt", 0),
                        ("reduced_weekly__lt", models.F("weekly")),
                    ),
                    _connector="OR",
                ),
                name="rateband_reduced_weekly_lt_base",
            ),
        ),
        migrations.AddConstraint(
            model_name="rateband",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_poa", False),
                    models.Q(
                        ("reduction_percent__isnull", True),
                        ("reduced_nightly__isnull", True),
                        ("reduced_weekly__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="rateband_poa_excludes_reduction",
            ),
        ),
    ]
