# Generated by Django 5.2.14 on 2026-07-13 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0005_rateband_reduction"),
        ("properties", "0004_alter_propertydefaults_prices_entered_as_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rateplan",
            name="idempotency_key",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.AddConstraint(
            model_name="rateplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("property", "idempotency_key"),
                name="rateplan_idempotency_key_unique_per_property",
            ),
        ),
    ]
