# Generated by Django 5.2.14 on 2026-06-01 22:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0005_ratecard_legacy_id_rateplan_legacy_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="raterule",
            name="raterule_date_from_lte_date_to",
        ),
        migrations.AddConstraint(
            model_name="raterule",
            constraint=models.CheckConstraint(
                condition=models.Q(("date_from__lt", models.F("date_to"))),
                name="raterule_date_from_lt_date_to",
            ),
        ),
    ]
