# Generated by Django 5.2.14 on 2026-06-01 22:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0006_remove_raterule_raterule_date_from_lte_date_to_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="raterule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_poa", False),
                    models.Q(("nightly__isnull", True), ("weekly__isnull", True)),
                    _connector="OR",
                ),
                name="raterule_poa_excludes_price",
            ),
        ),
    ]
