# Generated by Django 5.2.14 on 2026-06-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0007_raterule_raterule_poa_excludes_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="rateplan",
            name="fallback_nightly",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Opt-in nightly rate used when no RateRule covers a night. NULL = no fallback (uncovered nights raise NoRateAvailable).",
                max_digits=12,
                null=True,
            ),
        ),
    ]
