# Generated by Django 5.2.14 on 2026-06-02 04:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0008_rateplan_fallback_nightly"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ratecard",
            name="changeover_weekday",
        ),
    ]
