# Generated by Django 5.2.14 on 2026-06-30 23:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0011_migrate_inclusion_to_propertyservice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rateplan",
            name="inclusion",
        ),
    ]
