# Generated by Django 5.2.14 on 2026-07-01 10:27
#
# GAP-056 Unit 2 (expand): introduce the RatePeriod date-axis level and repoint
# RateRule at it, backfilling periods for existing flat rules. RateCard and
# RateRule.date_from/date_to stay transitionally (dropped in Unit 9).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# NOTE: the periods-disjoint-per-plan EXCLUDE is deliberately NOT added here.
# It is a *contract* constraint: card-precedence (overlapping cards, engine
# Unit 3) and the legacy loader's incremental overlap-resolution (Unit 5) still
# legitimately produce transitionally-overlapping periods, so enforcing
# disjointness now would break them. `segment_card_rules` already guarantees the
# backfill below emits disjoint periods; the EXCLUDE lands in Unit 9 (contract)
# with the bands-disjoint-party EXCLUDE, once every producer is period-native.


def _backfill_periods(apps, schema_editor) -> None:  # type: ignore[no-untyped-def]
    from pricing.services.period_backfill import backfill_plan_periods

    rate_period = apps.get_model("pricing", "RatePeriod")
    rate_rule = apps.get_model("pricing", "RateRule")
    backfill_plan_periods(rate_period, rate_rule)


def _unbackfill_periods(apps, schema_editor) -> None:  # type: ignore[no-untyped-def]
    # Lossy, dev-stage reverse. This RunPython reverses FIRST, before the schema
    # reversals: the CHECK-swap reverse re-adds the strict `date_from < date_to`
    # constraint, which single-day rows (backfill fragments or operator-created)
    # would violate — so delete them here to let reverse complete. The `period`
    # column is dropped by a later reversal (before the RatePeriod table), so
    # rules are not cascade-deleted; fragment clones and rewritten rule dates are
    # not restored. Reverse is not a production path — re-run `loadlegacy` /
    # `seed_dev` to rebuild.
    rate_rule = apps.get_model("pricing", "RateRule")
    rate_rule.objects.filter(date_from=models.F("date_to")).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0012_drop_rateplan_inclusion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RatePeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("min_nights", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_nights", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
            ],
            options={
                "ordering": ["plan", "date_from"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="raterule",
            name="raterule_date_from_lt_date_to",
        ),
        migrations.AddField(
            model_name="rateperiod",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rateperiod",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periods",
                to="pricing.rateplan",
            ),
        ),
        migrations.AddField(
            model_name="rateperiod",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="raterule",
            name="period",
            field=models.ForeignKey(
                blank=True,
                help_text="GAP-056 date-axis parent. Nullable transitionally while `card`/dates still exist; populated by the `save()` shim on every write and made non-null when `RateCard` is dropped.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="pricing.rateperiod",
            ),
        ),
        migrations.AddConstraint(
            model_name="raterule",
            constraint=models.CheckConstraint(
                condition=models.Q(("date_from__lte", models.F("date_to"))),
                name="raterule_date_from_lte_date_to",
            ),
        ),
        migrations.AddIndex(
            model_name="rateperiod",
            index=models.Index(
                fields=["plan", "date_from", "date_to"], name="pricing_rat_plan_id_54dd48_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rateperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("date_from__lte", models.F("date_to"))),
                name="rateperiod_date_from_lte_date_to",
            ),
        ),
        migrations.RunPython(_backfill_periods, _unbackfill_periods, elidable=False),
    ]
