# Generated by Django 5.2.14 on 2026-07-01 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0013_rateperiod_hierarchy"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="discount",
            name="discount_card_or_property_required",
        ),
        migrations.RemoveIndex(
            model_name="discount",
            name="pricing_dis_card_id_07b941_idx",
        ),
        migrations.RemoveField(
            model_name="discount",
            name="card",
        ),
    ]
