# Generated by Django 5.2.14 on 2026-09-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0013_extra_legacy_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="rateband",
            name="is_indicative",
            field=models.BooleanField(default=False),
        ),
    ]
