# Generated by Django 5.2.14 on 2026-07-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0017_rateperiod_name_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="rateplan",
            name="prices_by_occupancy",
            field=models.BooleanField(
                default=False,
                help_text="False = one flat price per period (party size ignored); True = per-party-size RateBands.",
            ),
        ),
    ]
