"""factory-boy factories for the `properties` app.

These double as the canonical test-data builders and as the building blocks
the `seed_dev` management command composes. Faker drives realistic values;
unique fields combine a per-run `RUN_TOKEN` with a `factory.Sequence` so
additive seed runs never collide on a unique constraint (slug, name).

`CountryFactory` / `PropertyCategoryFactory` use `django_get_or_create` so
they reuse the rows pre-seeded by migrations instead of fighting unique
constraints.
"""

from __future__ import annotations

import functools
import io
import random
from datetime import date, timedelta
from decimal import Decimal
from pathlib import Path
from typing import Any, cast

import factory
import yaml
from django.conf import settings
from django.core.files.base import ContentFile
from factory.django import DjangoModelFactory
from faker import Faker
from PIL import Image

from accounts.enums import ContactRole
from core.factories import RUN_TOKEN
from properties import models
from properties.enums import (
    CommissionCalcType,
    DescriptionSection,
    FeatureServiceType,
    ImageKind,
    PrefilledChangeOverDay,
    PropertyChannel,
    PropertyStatus,
    RoomPlacement,
)
from properties.services.location import location_defaults

# Villa-rental markets. Every iso2 here is in the 249-row ISO-3166 seed
# (`properties.0009`), so `django_get_or_create=("iso2",)` resolves to the
# seeded row and the iso3/name defaults below are only a safety net.
_VILLA_COUNTRIES = [
    ("GB", "GBR", "United Kingdom"),
    ("FR", "FRA", "France"),
    ("ES", "ESP", "Spain"),
    ("IT", "ITA", "Italy"),
    ("GR", "GRC", "Greece"),
    ("PT", "PRT", "Portugal"),
]

_CATEGORIES = [
    ("Villa", "villa"),
    ("Apartment", "apartment"),
    ("Chalet", "chalet"),
    ("Townhouse", "townhouse"),
]

_faker = Faker("en_GB")

# Deterministic villa-name menu. Component lengths (7, 9, 10) are pairwise
# coprime, so indexing each list with the same `n` enumerates every
# combination — 630 distinct names — before any repeat. The RUN_TOKEN-derived
# offset rotates the start point per process, so additive `seed_dev` re-runs
# (which restart `factory.Sequence` at 0) don't replay the same window.
_VILLA_KINDS = ("Villa", "Casa", "Finca", "Quinta", "Chalet", "Mas", "Domaine")
_VILLA_FIRST = (
    "Azure",
    "Saffron",
    "Cypress",
    "Juniper",
    "Coral",
    "Indigo",
    "Amber",
    "Pearl",
    "Olive",
)
_VILLA_SECOND = (
    "Cove",
    "Ridge",
    "Tides",
    "Grove",
    "Bluff",
    "Lagoon",
    "Terrace",
    "Point",
    "Hollow",
    "Crest",
)
_VILLA_NAME_CYCLE = len(_VILLA_KINDS) * len(_VILLA_FIRST) * len(_VILLA_SECOND)
_VILLA_NAME_OFFSET = int(RUN_TOKEN, 16) % _VILLA_NAME_CYCLE


def villa_name(n: int) -> str:
    """Deterministic, evocative villa name — distinct for 630 consecutive `n`."""
    return (
        f"{_VILLA_KINDS[n % len(_VILLA_KINDS)]}"
        f" {_VILLA_FIRST[n % len(_VILLA_FIRST)]}"
        f" {_VILLA_SECOND[n % len(_VILLA_SECOND)]}"
    )


def _tiny_png() -> ContentFile:
    """A 1x1 PNG so `PropertyImage.image` (a required ImageField) is valid
    without shipping fixture binaries."""
    buf = io.BytesIO()
    Image.new("RGB", (1, 1)).save(buf, format="PNG")
    return ContentFile(buf.getvalue(), name="seed.png")


# A pool of committed villa imagery (generated by the `generate_seed_images`
# command from `manifest.yaml`) that the seeder draws from so dev/staging UIs
# show real villas instead of grey 1x1 placeholders. One subdirectory per
# villa, each holding `hero.jpg` / `interior.jpg` / `exterior.jpg` /
# `gallery.jpg`. The manifest is the single source of truth for both the
# imagery *and* the seeded property identity (name, location, description).
_SEED_IMAGE_ROOT = Path(settings.BASE_DIR) / "core" / "seed_data" / "villa_images"
_MANIFEST_PATH = _SEED_IMAGE_ROOT / "manifest.yaml"


@functools.cache
def villa_manifest() -> list[dict[str, Any]]:
    """Villa entries that have generated imagery on disk (a `hero.jpg`).

    Each entry is one "available image option": the `properties` seed stage
    cycles through this list, exhausting every villa before repeating, and uses
    each entry's `location_tag` / `country_iso2` / `style_anchor` to build a
    property coherent with its imagery. Names are not drawn from the manifest;
    `villa_name` generates them so they stay unique past 20 properties.

    Empty on a checkout without the generated pool, so the seeder falls back to
    random property data and tests are unaffected.
    """
    if not _MANIFEST_PATH.is_file():
        return []
    entries = yaml.safe_load(_MANIFEST_PATH.read_text()) or []
    return [e for e in entries if (_SEED_IMAGE_ROOT / e["slug"] / "hero.jpg").is_file()]


@functools.cache
def _villa_image_bytes(slug: str, kind: str) -> bytes | None:
    """Raw bytes of a committed villa image, cached per (slug, kind) so the
    small fixed corpus is read from disk once per process rather than re-read
    for every PropertyImage row. ``None`` when the file is absent."""
    path = _SEED_IMAGE_ROOT / slug / f"{kind}.jpg"
    if not path.is_file():
        return None
    return path.read_bytes()


def _villa_image_or_placeholder(slug: str | None, kind: str) -> ContentFile:
    """A ContentFile for the villa's image of this kind, falling back to the
    1x1 placeholder when there's no villa or no generated file (e.g. floor
    plans, which we deliberately don't generate). The bytes are cached, but
    ContentFile is a per-row stateful stream, so a fresh one is wrapped each
    call."""
    data = _villa_image_bytes(slug, kind) if slug else None
    return _tiny_png() if data is None else ContentFile(data, name=f"{kind}.jpg")


class CountryFactory(DjangoModelFactory):
    class Meta:
        model = models.Country
        django_get_or_create = ("iso2",)

    class Params:
        spec = factory.Iterator(_VILLA_COUNTRIES)

    iso2 = factory.LazyAttribute(lambda o: o.spec[0])
    iso3 = factory.LazyAttribute(lambda o: o.spec[1])
    name = factory.LazyAttribute(lambda o: o.spec[2])


class RegionFactory(DjangoModelFactory):
    class Meta:
        model = models.Region

    country = factory.SubFactory(CountryFactory)
    name = factory.Faker("city")
    slug = factory.Sequence(lambda n: f"region-{RUN_TOKEN}-{n}")


class PropertyCategoryFactory(DjangoModelFactory):
    class Meta:
        model = models.PropertyCategory
        django_get_or_create = ("slug",)

    class Params:
        spec = factory.Iterator(_CATEGORIES)

    name = factory.LazyAttribute(lambda o: o.spec[0])
    slug = factory.LazyAttribute(lambda o: o.spec[1])


class PropertyGroupFactory(DjangoModelFactory):
    class Meta:
        model = models.PropertyGroup

    # `properties.signals` auto-creates GroupSettings + GroupFinance on insert
    # (the rows `PropertySettings.effective()` / `PropertyFinance.effective()`
    # fall back to), so the factory must not create them again.
    name = factory.Sequence(lambda n: f"Portfolio {RUN_TOKEN}-{n}")


class FeatureCategoryFactory(DjangoModelFactory):
    class Meta:
        model = models.FeatureCategory
        django_get_or_create = ("slug",)

    name = factory.Sequence(lambda n: f"Feature group {RUN_TOKEN}-{n}")
    slug = factory.Sequence(lambda n: f"feature-group-{RUN_TOKEN}-{n}")


class FeatureFactory(DjangoModelFactory):
    class Meta:
        model = models.Feature

    category = factory.SubFactory(FeatureCategoryFactory)
    name = factory.Faker("word")
    slug = factory.Sequence(lambda n: f"feature-{RUN_TOKEN}-{n}")
    service_type = FeatureServiceType.AMENITY


class PropertyFactory(DjangoModelFactory):
    class Meta:
        model = models.Property
        skip_postgeneration_save = True

    name = factory.Sequence(lambda n: villa_name(n + _VILLA_NAME_OFFSET))
    display_name = factory.SelfAttribute("name")
    slug = factory.Sequence(lambda n: f"villa-{RUN_TOKEN}-{n}")
    status = PropertyStatus.ACTIVE
    channel = PropertyChannel.DIRECT
    category = factory.SubFactory(PropertyCategoryFactory)
    group = factory.SubFactory(PropertyGroupFactory)
    region = factory.SubFactory(RegionFactory)

    @factory.post_generation
    def children(obj: models.Property, create: bool, extracted: object, **kwargs: object) -> None:
        if not create:
            return
        # Optional manifest villa (fed by the `properties` seed stage via
        # `PropertyFactory(children__villa=...)`) so the description and hero
        # image match the villa whose identity the stage assigned this property.
        villa = cast("dict[str, Any] | None", kwargs.get("villa"))
        models.PropertyLocation.objects.create(
            property=obj,
            **location_defaults(obj),
            address_line_1=_faker.street_address(),
            locality_town=obj.region.name,
            post_code=_faker.postcode(),
        )
        models.PropertyCapacity.objects.create(
            property=obj,
            guests=8,
            bedrooms=4,
            bathrooms=3,
            ensuites=2,
        )
        # All-null PropertySettings/PropertyFinance => inherit from the group.
        models.PropertySettings.objects.create(property=obj)
        models.PropertyFinance.objects.create(property=obj)
        models.PropertyDescription.objects.create(
            property=obj,
            section=DescriptionSection.OVERVIEW,
            body=villa["style_anchor"].strip() if villa else _faker.paragraph(),
        )
        villa_slug = villa["slug"] if villa else None
        models.PropertyImage.objects.create(
            property=obj,
            image=_villa_image_or_placeholder(villa_slug, ImageKind.HERO.value),
            kind=ImageKind.HERO,
            name="Hero",
        )

    @factory.post_generation
    def with_owner_contact(
        obj: models.Property,
        create: bool,
        extracted: object,
        **kwargs: object,
    ) -> None:
        """Opt-in: attach a Contact + commission terms to the finance row.

        Default off (preserves legacy "all-null finance, inherit from group"
        shape). Set to True via ``PropertyFactory(with_owner_contact=True)`` —
        the seeded Contact gets a primary `ContactEmail` and `ContactPhone`,
        and the finance row gets a mix of percent / fixed commission so the
        Owner tab renders both branches in dev/staging.
        """
        if not create or not extracted:
            return
        # Local imports: `accounts.factories` already imports from us, and
        # the `accounts` models live in a different app graph.
        from accounts.factories import (
            ContactEmailFactory,
            ContactFactory,
            ContactPhoneFactory,
        )
        from accounts.models import Contact

        # `get_or_create` rather than `obj.finance` removes the implicit
        # dependency on the sibling `children` post_generation hook having
        # already created the PropertyFinance row.
        finance, _ = models.PropertyFinance.objects.get_or_create(property=obj)
        contact = cast(
            Contact,
            ContactFactory(address_line_1=_faker.street_address(), address_line_2=""),
        )
        # Pin `is_primary` explicitly so a future change to the email/phone
        # factory default doesn't silently break the Owner-tab serializer,
        # which reads the primary row.
        ContactEmailFactory(contact=contact, is_primary=True)
        ContactPhoneFactory(contact=contact, is_primary=True)
        # Mirror the finance link with a primary OWNER assignment so
        # `primary_owner_email()` (which keys off PropertyContactAssignment,
        # not finance.contact) resolves and the owner-approval email fires
        # on pre-approval bookings.
        models.PropertyContactAssignment.objects.create(
            property=obj,
            contact=contact,
            role=ContactRole.OWNER,
            is_primary=True,
        )
        finance.contact = contact
        # Mix percent / fixed so the Owner tab renders both formatter branches.
        if random.random() < 0.7:
            finance.commission_calculation_type = CommissionCalcType.PERCENT.value
            finance.commission_amount = Decimal("12.50")
        else:
            finance.commission_calculation_type = CommissionCalcType.FIXED.value
            finance.commission_amount = Decimal("500.00")
        finance.commission_note = "Owner agreed terms"
        finance.save(
            update_fields=[
                "contact",
                "commission_calculation_type",
                "commission_amount",
                "commission_note",
                "updated_at",
            ]
        )


class RoomFactory(DjangoModelFactory):
    class Meta:
        model = models.Room
        skip_postgeneration_save = True

    property = factory.SubFactory(PropertyFactory)
    name = factory.Sequence(lambda n: f"Bedroom {n}")
    placement = RoomPlacement.MAIN_HOUSE

    @factory.post_generation
    def beds(obj: models.Room, create: bool, extracted: object, **kwargs: object) -> None:
        if create:
            models.RoomBeds.objects.create(room=obj, double=1)


class NearbyPlaceTypeFactory(DjangoModelFactory):
    """Canonical lookup: NearbyPlaceType.name is unique, so reuse seeded rows
    on rerun via get_or_create."""

    class Meta:
        model = models.NearbyPlaceType
        django_get_or_create = ("name",)

    name = factory.Sequence(lambda n: f"place-type-{RUN_TOKEN}-{n}")


class PropertyNearbyPlaceFactory(DjangoModelFactory):
    class Meta:
        model = models.PropertyNearbyPlace

    property = factory.SubFactory(PropertyFactory)
    place_type = factory.SubFactory(NearbyPlaceTypeFactory)
    name = factory.Faker("city")
    distance_km = Decimal("2.50")


class CollectionFactory(DjangoModelFactory):
    """`Collection.slug` is globally unique; combine RUN_TOKEN+Sequence so
    additive seed runs do not collide on the unique constraint."""

    class Meta:
        model = models.Collection

    name = factory.Sequence(lambda n: f"Collection {RUN_TOKEN}-{n}")
    slug = factory.Sequence(lambda n: f"collection-{RUN_TOKEN}-{n}")
    description = "Curated collection of villas (seeded)."


class PropertyContactAssignmentFactory(DjangoModelFactory):
    """Active-role assignment. Defaults `is_primary=False` so the
    `one_primary_per_role` partial-unique constraint does not collide when
    multiple assignments per (property, role) are seeded."""

    class Meta:
        model = models.PropertyContactAssignment

    property = factory.SubFactory(PropertyFactory)
    # Caller supplies a Contact — accounts.factories.ContactFactory lives in
    # a sibling app and importing it here would create a cycle.
    role = ContactRole.HOUSEKEEPER
    is_primary = False


class ChangeOverRuleFactory(DjangoModelFactory):
    class Meta:
        model = models.ChangeOverRule

    property = factory.SubFactory(PropertyFactory)
    day = PrefilledChangeOverDay.SAT
    starts_on = factory.LazyFunction(date.today)
    ends_on = factory.LazyAttribute(lambda o: o.starts_on + timedelta(days=60))
    notes = "Peak-season Saturday changeovers (seeded)."


class PropertyCalendarFeedFactory(DjangoModelFactory):
    """A per-villa iCal feed. `url` is `RUN_TOKEN`-unique so additive runs don't
    collide on the `(property, url)` constraint. `platform` defaults to OTHER via
    the model default."""

    class Meta:
        model = models.PropertyCalendarFeed

    property = factory.SubFactory(PropertyFactory)
    url = factory.Sequence(lambda n: f"https://example.test/ical/{RUN_TOKEN}-{n}.ics")
    label = factory.Sequence(lambda n: f"Feed {RUN_TOKEN}-{n}")
    is_active = True
